"""ORM models. One table per entity, no inheritance tricks."""

from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    desc,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base

# Timestamps are stored as timestamptz and generated by the database, so every row
# agrees on the clock even with several application instances.
TimestampTZ = DateTime(timezone=True)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(String(320), unique=True)
    password_hash: Mapped[str] = mapped_column(Text)
    full_name: Mapped[str | None] = mapped_column(String(200))
    role: Mapped[str] = mapped_column(String(20), default="customer")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TimestampTZ, server_default=func.now(), onupdate=func.now()
    )
    last_login_at: Mapped[datetime | None] = mapped_column(TimestampTZ)
    # Every token carries the epoch it was minted at; only the current one is accepted.
    # Bumping this ends every session the account has, which is what a password change
    # must do — the tokens are stateless, so revocation has to live on the account.
    # A counter rather than a timestamp because JWT `iat` holds whole seconds, and a
    # token minted in the same second as the change would survive a time comparison.
    token_epoch: Mapped[int] = mapped_column(Integer, default=0, server_default="0")

    __table_args__ = (
        CheckConstraint("role in ('customer', 'admin', 'worker')", name="role_known"),
        Index("ix_users_role", "role"),
    )


class AuditEntry(Base):
    __tablename__ = "audit_entries"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    request_id: Mapped[str] = mapped_column(String(64))
    # The actor may be deleted later; the trail keeps the email either way, which is
    # why it is denormalised rather than joined.
    actor_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    actor_email: Mapped[str | None] = mapped_column(String(320))
    method: Mapped[str] = mapped_column(String(10))
    path: Mapped[str] = mapped_column(String(512))
    status_code: Mapped[int] = mapped_column(Integer)
    target_type: Mapped[str | None] = mapped_column(String(50))
    target_id: Mapped[str | None] = mapped_column(String(64))
    changes: Mapped[dict | None] = mapped_column(JSONB)
    ip: Mapped[str | None] = mapped_column(String(45))
    user_agent: Mapped[str | None] = mapped_column(String(512))
    duration_ms: Mapped[int] = mapped_column(Integer)

    __table_args__ = (
        # The trail is read newest-first and filtered by actor or time far more often
        # than anything else.
        Index("ix_audit_entries_id_desc", id.desc()),
        Index("ix_audit_entries_created_at", created_at.desc()),
        Index("ix_audit_entries_actor_id", actor_id),
    )


class LoginAttempt(Base):
    """Failed sign-ins, counted per account and per address.

    One row per bucket rather than one per attempt: the limiter only ever needs the
    running count and the current lock, and a row per attempt would make sign-in pay
    for an ever-growing table.
    """

    __tablename__ = "login_attempts"

    scope: Mapped[str] = mapped_column(String(10), primary_key=True)
    key: Mapped[str] = mapped_column(String(320), primary_key=True)
    failures: Mapped[int] = mapped_column(Integer, default=0)
    window_start: Mapped[datetime] = mapped_column(TimestampTZ)
    locked_until: Mapped[datetime | None] = mapped_column(TimestampTZ)
    updated_at: Mapped[datetime] = mapped_column(TimestampTZ)

    __table_args__ = (
        CheckConstraint("scope in ('ip', 'account')", name="scope_known"),
        # Buckets nobody has touched for a while are prunable; nothing else reads this.
        Index("ix_login_attempts_updated_at", "updated_at"),
    )


class Currency(Base):
    """ISO 4217. Reference data, keyed by the code everything else already speaks."""

    __tablename__ = "currencies"

    # Natural key: the code is what arrives in every feed and appears in every URL, so a
    # surrogate id would add a join to almost every query and buy nothing.
    code: Mapped[str] = mapped_column(String(3), primary_key=True)
    name: Mapped[str] = mapped_column(String(100))
    symbol: Mapped[str | None] = mapped_column(String(8))
    # How many decimal places the currency actually has. Two almost everywhere, zero for
    # the yen, three for a few others. It is what says Numeric(12, 2) is the right shape,
    # and the only thing that catches a second currency with different precision.
    minor_units: Mapped[int] = mapped_column(SmallInteger, default=2, server_default="2")

    __table_args__ = (
        CheckConstraint("code = upper(code)", name="code_upper"),
        CheckConstraint("minor_units between 0 and 4", name="minor_units_sane"),
    )


class Country(Base):
    """ISO 3166-1 alpha-2, and the facts that are true whether or not we sell there.

    Not the same thing as a market: a shop in Germany may deliver to Riga while we run no
    German storefront at all. Germany still needs a row here, for its VAT rate and for the
    shop to point at.
    """

    __tablename__ = "countries"

    code: Mapped[str] = mapped_column(String(2), primary_key=True)
    name: Mapped[str] = mapped_column(String(100))
    currency_code: Mapped[str] = mapped_column(ForeignKey("currencies.code"))
    # Standard rate, as a fraction: 0.2100, not 21. It is multiplied, never divided by a
    # hundred somewhere further down.
    #
    # Nullable because an unknown rate has to look unknown. Nothing is computed from this
    # — prices are stored exactly as the buyer sees them — so the rate only ever explains
    # why two prices differ, and a wrong one explains it wrongly and silently.
    #
    # Current rate, not a history: rates change, and when one does this column is updated
    # and past explanations quietly become wrong. That is acceptable only as long as no
    # arithmetic depends on it. The day it does, this becomes a table with valid_from.
    vat_standard_rate: Mapped[Decimal | None] = mapped_column(Numeric(5, 4))
    # Customs, duty and the cross-border VAT rules all differ across this line, so what
    # can be promised to a buyer differs with it.
    is_eu: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")

    __table_args__ = (
        CheckConstraint("code = upper(code)", name="code_upper"),
        CheckConstraint(
            "vat_standard_rate is null or vat_standard_rate between 0 and 1",
            name="vat_is_a_fraction",
        ),
        Index("ix_countries_is_eu", "is_eu"),
    )


class Market(Base):
    """A storefront we run, in one country.

    Not the same thing as a country: `countries` holds every country we have to be able
    to describe — a German shop delivering to Riga needs a row there — while a market is
    a country we have decided to sell in. One storefront per country, which is why the
    country code is the key rather than a column next to one: two markets in the same
    country are impossible by construction rather than by convention.

    Not seeded. Countries and currencies are facts about the world and belong in a
    migration; opening a market is a decision, and it is made through the admin panel so
    that adding one is data rather than a release.
    """

    __tablename__ = "markets"

    # Primary key and foreign key at once, and what `offer` and `price_event` will carry
    # — two characters instead of an eight-byte id is worth a couple of gigabytes there.
    code: Mapped[str] = mapped_column(String(2), ForeignKey("countries.code"), primary_key=True)
    name: Mapped[str] = mapped_column(String(100))
    # The path segment: /lv/, or /latvija/ if that reads better locally. Kept separate
    # from the code rather than derived from it, because the URL is a product decision
    # and the ISO code is not, and moving a URL after launch costs search ranking.
    #
    # Entered, never generated from the name: deriving it would mean a rename silently
    # moves the URL. And this is the one slug in the system where a change moves every
    # page of a storefront rather than a single one, so it needs a redirect story before
    # it is ever edited, not after.
    slug: Mapped[str] = mapped_column(String(32), unique=True)
    # ISO 639-1, ordered, the first one is the default. A language is not a market: the
    # prices, the shops and the delivery are the same whichever one the page is read in,
    # so Russian in Latvia is a toggle here, not a second storefront.
    languages: Mapped[list[str]] = mapped_column(ARRAY(Text))
    # Created, wired into the parsers, mapped, and only then shown. Adding a market is a
    # process, and this is what makes it one.
    is_enabled: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")

    __table_args__ = (
        CheckConstraint("code = upper(code)", name="code_upper"),
        CheckConstraint("cardinality(languages) > 0", name="has_a_language"),
        # A malformed slug is a 404 that looks like an application bug.
        CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),
    )


class Category(Base):
    """The tree products hang from, and the lever over what the storefront shows.

    Two states that have nothing to do with each other: `is_visible` is editorial, and
    `identity_ready` says whether the parser knows how to pull this category's variant
    axes out of an offer. A category can be created and shown long before it is ready —
    its variants simply take the slow path through the matcher.
    """

    __tablename__ = "categories"

    id: Mapped[int] = mapped_column(primary_key=True)
    parent_id: Mapped[int | None] = mapped_column(ForeignKey("categories.id"))
    # Entered, not generated from the name: deriving it would let a rename move the URL.
    slug: Mapped[str] = mapped_column(String(64), unique=True)
    name: Mapped[str] = mapped_column(String(200))
    is_visible: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    # Own visibility AND every ancestor's, recomputed whenever the tree changes. Walking
    # ancestors per query does not survive millions of variants, and a storefront filter
    # has to be a boolean on an index rather than a recursion.
    is_visible_effective: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    identity_ready: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")
    # Whether the model rung may place a listing on an entry that agrees with it only on the
    # axes both happen to carry. A phone has two axes and a model names few of them; a
    # laptop has seven and a model names dozens of configurations, and on bigbox's first
    # laptop run 234 of 392 model matches were made on an incomplete identity — a
    # ThinkBook whose chip was not read placed on the one with `7 240H`.
    model_match_needs_full_identity: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false"
    )
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TimestampTZ, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),
        CheckConstraint("parent_id is null or parent_id <> id", name="not_its_own_parent"),
        Index("ix_categories_parent_id", "parent_id"),
        # What the storefront filters on.
        Index("ix_categories_visible_effective", "is_visible_effective"),
    )


class Attribute(Base):
    """One canonical registry, because sources name the same thing a dozen ways.

    `Цвет`, `Color`, `Krāsa` and `Spalva` all resolve here, which is what makes a feed
    param and a phrase cut out of a title interchangeable: once both become
    `capacity = 256 GB`, where the value came from stops mattering downstream.

    An attribute is one attribute only if its values mean the same thing everywhere. Size
    42 in shoes and size 42 in clothing are different scales, so they are two.
    """

    __tablename__ = "attributes"

    id: Mapped[int] = mapped_column(primary_key=True)
    key: Mapped[str] = mapped_column(String(64), unique=True)
    name: Mapped[str] = mapped_column(String(200))
    value_type: Mapped[str] = mapped_column(String(10))
    # Only for numbers. The unit everything is converted to, and how far it is rounded —
    # without a fixed scale, 39.624 and 39.62 describe one screen and hash to two keys.
    unit_dimension: Mapped[str | None] = mapped_column(String(20))
    scale: Mapped[int | None] = mapped_column(SmallInteger)
    # What a person reads, by language: `{"lv": "Operatīvā atmiņa", "ru": "Оперативная
    # память"}`. `name` stays the one the registry is kept in; a label is only shown.
    labels: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")

    __table_args__ = (
        CheckConstraint("key ~ '^[a-z][a-z0-9_]*$'", name="key_shape"),
        CheckConstraint(
            "value_type in ('enum', 'number', 'bool', 'text')", name="value_type_known"
        ),
        # A unit and a rounding scale only mean something for a number.
        CheckConstraint(
            "(value_type = 'number') or (unit_dimension is null and scale is null)",
            name="units_are_for_numbers",
        ),
        CheckConstraint("scale is null or scale between 0 and 6", name="scale_sane"),
    )


class AttributeAlias(Base):
    """What a source called it. `Krāsa` -> color.

    Not unique on the string alone: `Размер` is a real name for both shoe size and
    clothing size. Which one an offer means is settled by the category it landed in,
    through `category_attributes` — the same way an ambiguous brand string is.
    """

    __tablename__ = "attribute_aliases"

    id: Mapped[int] = mapped_column(primary_key=True)
    attribute_id: Mapped[int] = mapped_column(ForeignKey("attributes.id", ondelete="CASCADE"))
    alias_normalized: Mapped[str] = mapped_column(String(200))
    language: Mapped[str | None] = mapped_column(String(2))
    origin: Mapped[str] = mapped_column(String(10), default="human", server_default="human")

    __table_args__ = (
        UniqueConstraint("attribute_id", "alias_normalized", name="uq_alias_per_attribute"),
        CheckConstraint("origin in ('rule', 'judge', 'human')", name="origin_known"),
        Index("ix_attribute_aliases_normalized", "alias_normalized"),
    )


class CategoryAlias(Base):
    """A name a shop gives this category, in the language it gives it in.

    Two jobs, and the second is why this is a table rather than a list in a module.

    A shop puts the kind of thing at the front of a title — `Telefons Apple iPhone 18 Pro
    Max 256GB Burgundy` — and that word carries no model, so reading a model out of a title
    means knowing which words name the category. They are Latvian words. Written into a
    rule they are vocabulary in code, which is the thing we keep having to take back out;
    written here they are rows, and a Lithuanian shop needs rows rather than a rewrite.

    The same rows answer the other question nobody has answered yet: which of our categories
    a shop's own section path means. `Mobilie telefoni` and `Telefoni` are both this
    category said by two shops, which is exactly what an alias is.
    """

    __tablename__ = "category_aliases"

    id: Mapped[int] = mapped_column(primary_key=True)
    category_id: Mapped[int] = mapped_column(ForeignKey("categories.id", ondelete="CASCADE"))
    alias_normalized: Mapped[str] = mapped_column(String(200))
    # ISO 639-1, or null for a name that belongs to no particular language.
    language: Mapped[str | None] = mapped_column(String(2))
    origin: Mapped[str] = mapped_column(String(10), default="human", server_default="human")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        UniqueConstraint("category_id", "alias_normalized", name="uq_alias_per_category"),
        CheckConstraint("origin in ('rule', 'judge', 'human')", name="origin_known"),
        # Not unique on the string alone: a word can name two categories, and which one a
        # listing means is settled by where it came from rather than by the word.
        Index("ix_category_aliases_normalized", "alias_normalized"),
    )


class CategoryAttribute(Base):
    """Which attributes a category has, and which of them carry identity there.

    The flag sits on the pairing rather than on the attribute because the answer genuinely
    differs: weight is an axis for food — 500 g and 1 kg are different products — and a
    specification for a washing machine.
    """

    __tablename__ = "category_attributes"

    category_id: Mapped[int] = mapped_column(
        ForeignKey("categories.id", ondelete="CASCADE"), primary_key=True
    )
    attribute_id: Mapped[int] = mapped_column(
        ForeignKey("attributes.id", ondelete="CASCADE"), primary_key=True
    )
    identity_bearing: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")
    position: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    # Same attribute, different label here: "Diagonal" on a phone, "Screen size" on a TV.
    label_override: Mapped[str | None] = mapped_column(String(200))
    # Stored in the base unit, shown in this one.
    display_unit: Mapped[str | None] = mapped_column(String(20))

    __table_args__ = (Index("ix_category_attributes_attribute_id", "attribute_id"),)


class AttributeValue(Base):
    """A canonical value of an enum attribute. Only enums have these."""

    __tablename__ = "attribute_values"

    id: Mapped[int] = mapped_column(primary_key=True)
    attribute_id: Mapped[int] = mapped_column(ForeignKey("attributes.id", ondelete="CASCADE"))
    canonical: Mapped[str] = mapped_column(String(200))
    # The value as a person reads it, by language: `black` is `melns` and `чёрный`. The
    # canonical string is what the readings produce and the matcher compares, and it is
    # never renamed for display's sake.
    labels: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")
    # Display order, because S / M / L / XL is not alphabetical.
    position: Mapped[int] = mapped_column(Integer, default=0, server_default="0")

    __table_args__ = (UniqueConstraint("attribute_id", "canonical", name="uq_value_per_attribute"),)


class AttributeValueAlias(Base):
    """`melns`, `juodas`, `must`, `чёрный` -> black.

    `attribute_id` is repeated here so the unique constraint can span it: one spelling
    must not resolve to two values of the same attribute, and the value id alone cannot
    express that.
    """

    __tablename__ = "attribute_value_aliases"

    id: Mapped[int] = mapped_column(primary_key=True)
    attribute_value_id: Mapped[int] = mapped_column(
        ForeignKey("attribute_values.id", ondelete="CASCADE")
    )
    attribute_id: Mapped[int] = mapped_column(ForeignKey("attributes.id", ondelete="CASCADE"))
    alias_normalized: Mapped[str] = mapped_column(String(200))
    language: Mapped[str | None] = mapped_column(String(2))
    origin: Mapped[str] = mapped_column(String(10), default="human", server_default="human")

    __table_args__ = (
        UniqueConstraint("attribute_id", "alias_normalized", name="uq_value_alias_per_attribute"),
        CheckConstraint("origin in ('rule', 'judge', 'human')", name="origin_known"),
        Index("ix_attribute_value_aliases_normalized", "alias_normalized"),
    )


class Brand(Base):
    """What is written on the box, not who owns the factory.

    Procter & Gamble is not a brand, Ariel is: the string that ends up in a title and in a
    feed's brand field is the one the matcher has to recognise, so that is what is stored.

    The name is deliberately not unique. Delta is taps, an airline and machine tools —
    separate companies that happen to share a name, so they are separate rows. The slug is
    what is unique, which is why one of them ends up as `delta-tools`.
    """

    __tablename__ = "brands"

    id: Mapped[int] = mapped_column(primary_key=True)
    slug: Mapped[str] = mapped_column(String(64), unique=True)
    canonical_name: Mapped[str] = mapped_column(String(200))
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),)


class BrandAlias(Base):
    """Another way a source writes the brand, or a line the brand makes.

    Those are not the same thing, and `kind` is what keeps them apart. `Самсунг` and
    `Samsungo` *are* Samsung; `iPhone` is a line Apple makes. A feed's brand field saying
    `iPhone` does mean Apple, but reading it out of a title files "Spigen case for
    iPhone 15" under Apple — and every catalogue holds more accessories than devices, so
    that is the main flow of errors rather than an edge case.

    Not unique on the string alone: `Delta` legitimately belongs to two brands. Which one
    an offer means is settled by the category it landed in, from the brands that already
    have variants there.
    """

    __tablename__ = "brand_aliases"

    id: Mapped[int] = mapped_column(primary_key=True)
    brand_id: Mapped[int] = mapped_column(ForeignKey("brands.id", ondelete="CASCADE"))
    # Case, punctuation and legal suffixes are computed away rather than stored, so
    # `SAMSUNG®` and `Samsung` are one row. A declension is not derivable by any rule and
    # stays a row of its own: Lithuanian declines foreign names as grammar.
    alias_normalized: Mapped[str] = mapped_column(String(200))
    alias_raw: Mapped[str] = mapped_column(String(200))
    kind: Mapped[str] = mapped_column(String(10), default="spelling", server_default="spelling")
    origin: Mapped[str] = mapped_column(String(10), default="human", server_default="human")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        UniqueConstraint("brand_id", "alias_normalized", name="uq_alias_per_brand"),
        CheckConstraint("kind in ('spelling', 'line')", name="kind_known"),
        CheckConstraint("origin in ('rule', 'judge', 'human')", name="origin_known"),
        # The matcher's lookup: one string in, one or more brands out.
        Index("ix_brand_aliases_normalized", "alias_normalized"),
    )


class AttributeValueDismissal(Base):
    """A word a shop writes for an attribute that is deliberately not one of its values.

    `melna, pelēka` in a colour field is two colours, and not resolving it is right: a
    product filed under one of them is filed wrong. Marked so the list of what the registry
    does not know stops showing it — the one thing about that list worth storing, since
    everything else on it is computed from the readings as they are.
    """

    __tablename__ = "attribute_value_dismissals"

    attribute_id: Mapped[int] = mapped_column(
        ForeignKey("attributes.id", ondelete="CASCADE"), primary_key=True
    )
    # Casefolded and trimmed, as the list groups what shops wrote.
    value_normalized: Mapped[str] = mapped_column(String(200), primary_key=True)
    note: Mapped[str | None] = mapped_column(String(500))
    dismissed_by: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    dismissed_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    @staticmethod
    def key(value: str) -> str:
        """How a shop's word is grouped and marked. Here rather than in either feature,
        because the one that marks and the one that lists have to agree on it."""
        return value.strip().casefold()


class ModelAlias(Base):
    """`galaxy s26 5g`, `s26`, `galaxy s26` -> `Galaxy S26`, under Samsung.

    Which words in a title are the model is the same kind of fact as which words are a
    colour: a vocabulary, not a structure, so it is rows rather than a rule. The reader
    finds the longest of these whole in a title and takes `model` as the spelling — which
    is what makes twelve shops arrive at one catalogue name instead of twelve, and what
    stops a shop with no model field naming a product after its spec sheet.

    Per brand, because a model name only means something beside its maker: `Note 17` is a
    Xiaomi and, one day, somebody else's too. And per category, because a maker's names for
    its phones are not its names for its tablets: with the registry keyed by brand alone,
    Nubia's phone `Air` was found whole in `Apple iPad Air` and 130 tablets would have read
    as it. A category reads only its own page of names. The canonical spelling is a string rather
    than a row of its own, the way `category_aliases` does it: the registry is consulted
    by the reader and never joined to the catalogue, and a canonical that was a foreign
    key would tie a reading to a product row that may not exist yet.
    """

    __tablename__ = "model_aliases"

    id: Mapped[int] = mapped_column(primary_key=True)
    brand_id: Mapped[int] = mapped_column(ForeignKey("brands.id", ondelete="CASCADE"))
    category_id: Mapped[int] = mapped_column(ForeignKey("categories.id", ondelete="CASCADE"))
    # Words, casefolded, separated by single spaces, and nothing else kept but `+`: it is
    # the one mark that tells two models apart — `Galaxy S26+` is not `Galaxy S26`.
    alias_normalized: Mapped[str] = mapped_column(String(200))
    # The spelling the catalogue uses. Several aliases point at one of these.
    model: Mapped[str] = mapped_column(String(200))
    origin: Mapped[str] = mapped_column(String(10), default="human", server_default="human")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        UniqueConstraint(
            "category_id", "brand_id", "alias_normalized", name="uq_model_alias_per_category"
        ),
        CheckConstraint("origin in ('rule', 'judge', 'human')", name="origin_known"),
        Index("ix_model_aliases_normalized", "alias_normalized"),
    )


class Product(Base):
    """The family a human searches for: "iPhone 15 Pro".

    A grouping, not a thing you can buy — it has no price and no barcode. It is allowed to
    contain exactly one variant, which is the normal case for a book or a specific tool;
    inventing a hierarchy where the category has none would be worse than the duplication.
    """

    __tablename__ = "products"

    id: Mapped[int] = mapped_column(primary_key=True)
    # Derived from the title with the id appended, because a machine creates these by the
    # million and nobody can name them by hand. The tail is also what keeps a retitle from
    # breaking the link.
    slug: Mapped[str] = mapped_column(String(160), unique=True)
    brand_id: Mapped[int] = mapped_column(ForeignKey("brands.id"))
    category_id: Mapped[int] = mapped_column(ForeignKey("categories.id"))
    # The marketing designation, and one of the strongest language-neutral signals the
    # matcher has: a Latvian, Lithuanian and Estonian title share almost nothing except
    # the brand and this.
    model: Mapped[str] = mapped_column(String(200))
    # Generated from brand and model. Kept rather than computed on read so that sorting
    # and searching have something to work on.
    title: Mapped[str] = mapped_column(String(400))
    # Wins over the generated title and survives regeneration. Without it a generated
    # title could never be corrected.
    title_override: Mapped[str | None] = mapped_column(String(400))
    # Declared and deliberately unfilled: nothing writes a description yet, and it is not
    # yet decided whether anything will.
    description: Mapped[str | None] = mapped_column(Text)
    # The manufacturer's own page for this model, when somebody bothers to paste one.
    manufacturer_url: Mapped[str | None] = mapped_column(String(1000))
    is_visible: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TimestampTZ, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),
        Index("ix_products_brand_id", "brand_id"),
        Index("ix_products_category_id", "category_id"),
    )


class Variant(Base):
    """The unit that is bought, and what an offer attaches to.

    The primary entity of the catalogue. An offer linked at product level would put the
    price of a 128 GB phone in the same history as the 1 TB one.

    `product_id` is nullable: a variant created from an offer that matched nothing does not
    yet belong to a family, and inventing one from a single data point would be a guess.
    """

    __tablename__ = "variants"

    id: Mapped[int] = mapped_column(primary_key=True)
    slug: Mapped[str] = mapped_column(String(200), unique=True)
    product_id: Mapped[int | None] = mapped_column(ForeignKey("products.id", ondelete="SET NULL"))
    brand_id: Mapped[int] = mapped_column(ForeignKey("brands.id"))
    category_id: Mapped[int] = mapped_column(ForeignKey("categories.id"))
    model: Mapped[str] = mapped_column(String(200))
    # Repeated on the row in its matching form, next to the brand, because a model string
    # only means something beside its maker.
    model_normalized: Mapped[str] = mapped_column(String(200))
    title: Mapped[str] = mapped_column(String(400))
    title_override: Mapped[str | None] = mapped_column(String(400))
    description: Mapped[str | None] = mapped_column(Text)
    # Taken from one of the offers. A link to somebody else's CDN, which means it rots when
    # that shop removes the file — the real answer is to store the image ourselves, and
    # there is no file storage yet.
    image_url: Mapped[str | None] = mapped_column(String(1000))
    image_url_override: Mapped[str | None] = mapped_column(String(1000))
    kind: Mapped[str] = mapped_column(String(10), default="single", server_default="single")
    unit_count: Mapped[int] = mapped_column(Integer, default=1, server_default="1")
    # Computed from brand, category, model and the identity-bearing attributes — but only
    # when every one of them is present. Missing a single axis leaves it null and the
    # variant goes the long way round, because a key built from a partial set would
    # confidently merge two different things.
    identity_key: Mapped[str | None] = mapped_column(String(64), unique=True)
    is_visible: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TimestampTZ, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),
        CheckConstraint("kind in ('single', 'multipack', 'bundle')", name="kind_known"),
        CheckConstraint("unit_count > 0", name="unit_count_positive"),
        # A multipack is N of one thing and nothing else counts more than one.
        CheckConstraint("(kind = 'multipack') = (unit_count > 1)", name="only_multipacks_count"),
        Index("ix_variants_product_id", "product_id"),
        Index("ix_variants_category_id", "category_id"),
        # The matcher's blocking lookup: a model string is only meaningful beside a brand.
        Index("ix_variants_brand_model", "brand_id", "model_normalized"),
    )


class VariantAttribute(Base):
    """One attribute of one variant, reconciled across its offers.

    Typed columns rather than one text field: faceting and range filtering are the
    storefront — "6 to 7 inches", "256 GB (1 240)" — and casting a text column per query is
    not a way to serve that.
    """

    __tablename__ = "variant_attributes"

    variant_id: Mapped[int] = mapped_column(
        ForeignKey("variants.id", ondelete="CASCADE"), primary_key=True
    )
    attribute_id: Mapped[int] = mapped_column(
        ForeignKey("attributes.id", ondelete="CASCADE"), primary_key=True
    )
    value_num: Mapped[Decimal | None] = mapped_column(Numeric(20, 6))
    value_id: Mapped[int | None] = mapped_column(ForeignKey("attribute_values.id"))
    value_bool: Mapped[bool | None] = mapped_column(Boolean)
    value_text: Mapped[str | None] = mapped_column(Text)
    # A param outweighs something cut out of a title when offers disagree.
    source_kind: Mapped[str] = mapped_column(String(10), default="param", server_default="param")
    # A value a human set is never overwritten by reconciliation, or a correction lasts
    # exactly until the next crawl.
    origin: Mapped[str] = mapped_column(String(10), default="consensus", server_default="consensus")

    __table_args__ = (
        CheckConstraint("source_kind in ('param', 'title')", name="source_kind_known"),
        CheckConstraint("origin in ('consensus', 'human')", name="origin_known"),
        CheckConstraint(
            "num_nonnulls(value_num, value_id, value_bool, value_text) = 1",
            name="exactly_one_value",
        ),
        Index("ix_variant_attributes_enum", "attribute_id", "value_id"),
        Index("ix_variant_attributes_number", "attribute_id", "value_num"),
    )


class VariantGtin(Base):
    """A barcode a variant is known by. Plural on purpose.

    Regional packaging, a change of supplier and a reissue all give one variant another
    barcode; a single column would look obvious and become a lie within a month.
    """

    __tablename__ = "variant_gtins"

    variant_id: Mapped[int] = mapped_column(
        ForeignKey("variants.id", ondelete="CASCADE"), primary_key=True
    )
    gtin: Mapped[str] = mapped_column(String(14), primary_key=True)
    origin: Mapped[str] = mapped_column(String(10), default="rule", server_default="rule")
    first_seen_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        CheckConstraint("gtin ~ '^[0-9]{14}$'", name="gtin_digits"),
        CheckConstraint("origin in ('rule', 'judge', 'human')", name="origin_known"),
        # The strongest single lookup the matcher has. Not unique: sellers reuse and
        # mistype barcodes, so a clash is a conflict to record rather than a write to lose.
        Index("ix_variant_gtins_gtin", "gtin"),
    )


class VariantMpn(Base):
    """A manufacturer part number, which is only meaningful beside its brand."""

    __tablename__ = "variant_mpns"

    variant_id: Mapped[int] = mapped_column(
        ForeignKey("variants.id", ondelete="CASCADE"), primary_key=True
    )
    mpn_normalized: Mapped[str] = mapped_column(String(100), primary_key=True)
    # Denormalized from the variant so the blocking index can span the pair: two makers
    # reuse the same part number string freely.
    brand_id: Mapped[int] = mapped_column(ForeignKey("brands.id"))
    mpn_raw: Mapped[str] = mapped_column(String(100))
    origin: Mapped[str] = mapped_column(String(10), default="rule", server_default="rule")
    first_seen_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        CheckConstraint("origin in ('rule', 'judge', 'human')", name="origin_known"),
        Index("ix_variant_mpns_brand_mpn", "brand_id", "mpn_normalized"),
    )


class VariantComponent(Base):
    """What is inside a bundle.

    A bundle is different things sold together, so `unit_count` says nothing about it. It
    stays out of the single item's price comparison — listing a phone-with-case as the
    cheapest phone would be a lie — and this is how its price could one day be explained.
    """

    __tablename__ = "variant_components"

    bundle_id: Mapped[int] = mapped_column(
        ForeignKey("variants.id", ondelete="CASCADE"), primary_key=True
    )
    component_variant_id: Mapped[int] = mapped_column(
        ForeignKey("variants.id", ondelete="CASCADE"), primary_key=True
    )
    qty: Mapped[int] = mapped_column(Integer, default=1, server_default="1")

    __table_args__ = (
        CheckConstraint("qty > 0", name="qty_positive"),
        CheckConstraint("bundle_id <> component_variant_id", name="not_its_own_component"),
    )


class VariantMerge(Base):
    """Where a variant went when it turned out to be another one.

    A catalogue built from offers gets identity wrong and then learns better, so an id has
    to survive being merged away: the old one still resolves, the price history stays with
    the survivor, and an external link does not rot. Without this, a merge is a destructive
    write to the one table nothing else can be rebuilt from.
    """

    __tablename__ = "variant_merges"

    from_id: Mapped[int] = mapped_column(primary_key=True)
    into_id: Mapped[int] = mapped_column(ForeignKey("variants.id", ondelete="CASCADE"))
    merged_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    reason: Mapped[str | None] = mapped_column(String(500))
    decided_by: Mapped[str] = mapped_column(String(10), default="human", server_default="human")

    __table_args__ = (
        CheckConstraint("from_id <> into_id", name="not_into_itself"),
        CheckConstraint("decided_by in ('rule', 'judge', 'human')", name="decided_by_known"),
        Index("ix_variant_merges_into_id", "into_id"),
    )


class ProductMerge(Base):
    """The same, for a family. Lower stakes: regrouping is mostly moving variants."""

    __tablename__ = "product_merges"

    from_id: Mapped[int] = mapped_column(primary_key=True)
    into_id: Mapped[int] = mapped_column(ForeignKey("products.id", ondelete="CASCADE"))
    merged_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    reason: Mapped[str | None] = mapped_column(String(500))
    decided_by: Mapped[str] = mapped_column(String(10), default="human", server_default="human")

    __table_args__ = (
        CheckConstraint("from_id <> into_id", name="not_into_itself"),
        CheckConstraint("decided_by in ('rule', 'judge', 'human')", name="decided_by_known"),
        Index("ix_product_merges_into_id", "into_id"),
    )


class ShopGroup(Base):
    """One retail brand across several countries. Optional.

    MediaMarkt DE and MediaMarkt ES are different legal entities with different prices and
    different VAT, so they are different shops — but a buyer sees one logo. Nothing breaks
    when a shop has no group; most will not.
    """

    __tablename__ = "shop_groups"

    id: Mapped[int] = mapped_column(primary_key=True)
    slug: Mapped[str] = mapped_column(String(64), unique=True)
    name: Mapped[str] = mapped_column(String(200))

    __table_args__ = (CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),)


class Shop(Base):
    """The commercial party a buyer deals with.

    Not a source. The source is the channel we read bytes through, and its trust — a feed
    carrying barcodes is not a title scraped out of markup — has nothing to do with this
    shop's standing among buyers. One shop may have several sources, and that is the point:
    a feed and a scraper of the same shop converge on one offer instead of becoming two
    shops on a card.

    `country_code` points at `countries`, not at `markets`: a German shop delivering to
    Riga needs a row even though we run no German storefront.
    """

    __tablename__ = "shops"

    id: Mapped[int] = mapped_column(primary_key=True)
    shop_group_id: Mapped[int | None] = mapped_column(ForeignKey("shop_groups.id"))
    country_code: Mapped[str] = mapped_column(ForeignKey("countries.code"))
    slug: Mapped[str] = mapped_column(String(64), unique=True)
    name: Mapped[str] = mapped_column(String(200))
    website: Mapped[str | None] = mapped_column(String(1000))
    # Where the shop's logo is, for a page to show it by. A URL, not a file: the shop hosts
    # its own, and a copy here would go stale when it rebrands.
    logo_url: Mapped[str | None] = mapped_column(String(1000))
    # A marketplace holds many sellers behind one shop. An ordinary shop holds exactly one,
    # which is itself — created with it, because otherwise every shop needs a second call
    # that somebody will forget.
    is_marketplace: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")
    # What buyers think of it, which is not what we think of its feed.
    rating: Mapped[Decimal | None] = mapped_column(Numeric(3, 2))
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),
        CheckConstraint("rating is null or rating between 0 and 5", name="rating_range"),
        Index("ix_shops_country_code", "country_code"),
    )


class ShopMarket(Base):
    """Where a shop's offers are shown.

    Delivery is the reason, but the decision is ours: a shop may ship to Lithuania while we
    choose not to show it there yet. Hence a flag of its own — a shop can be switched off in
    one market without being touched in the others.
    """

    __tablename__ = "shop_markets"

    shop_id: Mapped[int] = mapped_column(
        ForeignKey("shops.id", ondelete="CASCADE"), primary_key=True
    )
    market_code: Mapped[str] = mapped_column(
        ForeignKey("markets.code", ondelete="CASCADE"), primary_key=True
    )
    is_enabled: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")

    __table_args__ = (Index("ix_shop_markets_market_code", "market_code"),)


class Source(Base):
    """One way into a shop, not the shop and not its website.

    A shop can have several, and they do not reach the same things: two shops of one group
    can run the same search engine behind the same code and differ only in which index is
    queried, one carrying barcodes for every product and the other for none. Calling that
    "a shop without barcodes" sends someone to parse titles for thousands of listings when
    the answer is a second channel into the same shop.

    `trust` belongs here rather than on the shop: data read out of a structured document is
    worth more than a value recovered from markup, and that says nothing about whether the
    shop is any good. When offers disagree, this is what breaks the tie.
    """

    __tablename__ = "sources"

    id: Mapped[int] = mapped_column(primary_key=True)
    shop_id: Mapped[int] = mapped_column(ForeignKey("shops.id", ondelete="CASCADE"))
    slug: Mapped[str] = mapped_column(String(64), unique=True)
    # How many requests a product costs, which is what decides the schedule. `wholesale`
    # returns everything in one request or a few pages; `retail` needs a listing and then
    # a request per product.
    access: Mapped[str] = mapped_column(String(10))
    # How a response turns into fields. The smallest and most replaceable part: most shops
    # already publish machine-readable product data inside the page, for search engines or
    # for their own front end, and reading markup is the fallback for what is left.
    decode: Mapped[str] = mapped_column(String(20))
    # Which facts each pass actually brings back. A property of the channel, not a general
    # rule: some listings carry stock and some carry only a price, and the difference
    # decides whether fresh availability costs a full crawl.
    delivers_full: Mapped[list[str]] = mapped_column(ARRAY(Text))
    delivers_quick: Mapped[list[str]] = mapped_column(ARRAY(Text), server_default="{}")
    # What this channel collects, when it collects one thing. Null for a feed that carries
    # the whole shop, where the category comes from the data instead. It is what selects
    # the category's reading rules: the same shape of code means different things to a
    # laptop and a monitor, and reading one by the other's rules is a silent wrong answer.
    category_id: Mapped[int | None] = mapped_column(
        ForeignKey("categories.id", ondelete="SET NULL")
    )
    trust: Mapped[str] = mapped_column(String(10), default="medium", server_default="medium")
    base_url: Mapped[str | None] = mapped_column(String(1000))
    is_enabled: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")
    # When each pass runs. An empty cron is how a pass is switched off; there is no second
    # flag beside it that could disagree with it.
    cron_full: Mapped[str | None] = mapped_column(String(64))
    cron_quick: Mapped[str | None] = mapped_column(String(64))
    # What this channel's own numbers have to look like for a run to be believed. Per
    # channel because fifteen items and nine hundred are both normal somewhere.
    min_items: Mapped[int | None] = mapped_column(Integer)
    max_drop_pct: Mapped[int] = mapped_column(SmallInteger, default=30, server_default="30")
    min_price_coverage: Mapped[Decimal] = mapped_column(
        Numeric(3, 2), default=Decimal("0.98"), server_default="0.98"
    )
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),
        CheckConstraint("access in ('wholesale', 'retail')", name="access_known"),
        # Scheduling a pass that brings back nothing is a config error, not a cheap run.
        CheckConstraint(
            "cron_quick is null or cardinality(delivers_quick) > 0",
            name="quick_cron_needs_a_quick_pass",
        ),
        CheckConstraint("min_items is null or min_items > 0", name="min_items_positive"),
        CheckConstraint("max_drop_pct between 0 and 100", name="drop_is_a_percentage"),
        CheckConstraint("min_price_coverage between 0 and 1", name="coverage_is_a_fraction"),
        CheckConstraint(
            "decode in ('json_ld', 'embedded_state', 'graphql', 'private_api', 'xml', 'markup')",
            name="decode_known",
        ),
        CheckConstraint("trust in ('high', 'medium', 'low')", name="trust_known"),
        CheckConstraint(
            "delivers_full <@ array['catalogue', 'price', 'availability']::text[]"
            " and cardinality(delivers_full) > 0",
            name="delivers_full_known",
        ),
        # A cheap pass cannot bring back more than an expensive one.
        CheckConstraint("delivers_quick <@ delivers_full", name="quick_within_full"),
        # A wholesale channel has no cheap pass: it is already everything.
        CheckConstraint(
            "access <> 'wholesale' or cardinality(delivers_quick) = 0",
            name="wholesale_has_no_quick_pass",
        ),
        Index("ix_sources_shop_id", "shop_id"),
    )


class Seller(Base):
    """Who is actually selling, within one shop.

    Price history is keyed by seller, so the word has to mean something exact. An ordinary
    shop has one, which is the shop. A marketplace has thousands, and treating the
    marketplace itself as the seller would draw a single price line through forty
    independent traders and present the gaps between them as movement.

    Deliberately not modelled: the same trader on two marketplaces. That is a second
    identity problem and it buys nothing for comparing prices.
    """

    __tablename__ = "sellers"

    id: Mapped[int] = mapped_column(primary_key=True)
    shop_id: Mapped[int] = mapped_column(ForeignKey("shops.id", ondelete="CASCADE"))
    # The shop's own id for the trader. For a shop that is its own seller, its slug.
    external_id: Mapped[str] = mapped_column(String(200))
    name: Mapped[str] = mapped_column(String(200))
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (UniqueConstraint("shop_id", "external_id", name="uq_seller_per_shop"),)


class Offer(Base):
    """One listing, as a thing that persists between crawls.

    Separate from `raw_offers` on purpose: the listing lives across fetches and the raw rows
    are observations of it. Merge the two and every crawl produces a new offer, so the match
    has to be made again from nothing each time and the price history restarts with it.

    Price and availability here are the latest reading — derived, recomputable, and kept
    only so a card does not have to walk the observations to show a number.
    """

    __tablename__ = "offers"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    seller_id: Mapped[int] = mapped_column(ForeignKey("sellers.id", ondelete="CASCADE"))
    # Which storefront this price is for. A German shop selling to a Latvian buyer charges
    # Latvian VAT, so the market is the one the price is quoted into, not the shop's own.
    market_code: Mapped[str] = mapped_column(ForeignKey("markets.code"))
    # The seller's own id for it. Together with the seller this is the listing's identity,
    # which is what lets two channels of one shop converge on one row.
    external_id: Mapped[str] = mapped_column(String(200))
    url: Mapped[str | None] = mapped_column(String(1000))
    condition: Mapped[str] = mapped_column(String(12), default="new", server_default="new")
    # As the source wrote it — "as new", "good". Not normalized, because grades are not
    # comparable between shops and normalizing them would invent a precision.
    condition_grade: Mapped[str | None] = mapped_column(String(50))
    price: Mapped[Decimal | None] = mapped_column(Numeric(12, 2))
    currency_code: Mapped[str | None] = mapped_column(ForeignKey("currencies.code"))
    availability: Mapped[str] = mapped_column(
        String(15), default="unknown", server_default="unknown"
    )
    # What the newest catalogue-carrying reading made of it, copied here for the same
    # reason as the price: a list of listings has to name and filter every row, and walking
    # the observations for each one cost 0.4 s a page over 18660 of them. A cheap pass is
    # passed over, because it carries no title — taken as current it would blank the name.
    title: Mapped[str | None] = mapped_column(String(1000))
    brand_raw: Mapped[str | None] = mapped_column(String(200))
    gtin: Mapped[str | None] = mapped_column(String(14))
    category_id: Mapped[int | None] = mapped_column(ForeignKey("categories.id"))
    first_seen_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    # A shop taking a listing down stops this moving. The offer stays, and so does every
    # price it ever had.
    last_seen_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        UniqueConstraint("seller_id", "external_id", name="uq_offer_per_seller"),
        CheckConstraint("condition in ('new', 'refurbished', 'used')", name="condition_known"),
        CheckConstraint(
            "availability in ('in_stock', 'out_of_stock', 'preorder', 'unknown')",
            name="availability_known",
        ),
        CheckConstraint("price is null or price >= 0", name="price_not_negative"),
        Index("ix_offers_market_code", "market_code"),
        Index("ix_offers_last_seen_at", "last_seen_at"),
        Index("ix_offers_gtin", "gtin"),
        Index("ix_offers_category_id", "category_id"),
    )


class RawOffer(Base):
    """What the shop actually served, kept verbatim.

    Bytes rather than fields picked out of them: storage is cheap, re-crawling is not, and
    the field nobody thought to extract in month one is the one the matcher needs in month
    four. Everything downstream is derived from this and can be thrown away.

    One row per distinct content, not per fetch. An unchanged page bumps `last_seen_at` and
    writes nothing, which is what keeps the table proportional to how much the world changes
    rather than to how often we look at it.
    """

    __tablename__ = "raw_offers"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    offer_id: Mapped[int] = mapped_column(ForeignKey("offers.id", ondelete="CASCADE"))
    # Which channel saw it. On the observation rather than on the offer, because a shop's
    # feed and its scraper are two channels onto one listing.
    source_id: Mapped[int] = mapped_column(ForeignKey("sources.id", ondelete="CASCADE"))
    # Which run brought it in. Null for anything submitted by hand, which is how a sample
    # is loaded. Worth the column: when a run is rejected or its coverage falls off a
    # cliff, the question is always "show me what that run actually saw", and a timestamp
    # only narrows it to a window.
    run_id: Mapped[int | None] = mapped_column(ForeignKey("runs.id", ondelete="SET NULL"))
    payload: Mapped[dict] = mapped_column(JSONB)
    content_hash: Mapped[str] = mapped_column(String(64))
    fetched_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    last_seen_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        UniqueConstraint("offer_id", "content_hash", name="uq_raw_per_content"),
        Index("ix_raw_offers_run_id", "run_id"),
        Index("ix_raw_offers_offer_id", "offer_id"),
        Index("ix_raw_offers_source_id", "source_id"),
    )


class NormalizedOffer(Base):
    """Our reading of one raw observation.

    A pure function of the payload and the ruleset version, which is the property the whole
    pipeline rests on: improving a rule means re-running it over what is already stored and
    comparing the old reading with the new one before accepting it. Never edited in place.

    Brand and category arrive as the strings a source wrote. Resolving them to rows is
    matching's job, not normalization's — and the unresolved string is what a candidate
    queue is filled from.
    """

    __tablename__ = "normalized_offers"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    raw_offer_id: Mapped[int] = mapped_column(ForeignKey("raw_offers.id", ondelete="CASCADE"))
    # Composed rather than opaque — `generic-1+phones-1+ksenukai-1+apple-phones-1` — so a
    # row says what produced it without a lookup. It grows by one layer at a time and the
    # first width it was given was outgrown the moment brands got theirs.
    ruleset_version: Mapped[str] = mapped_column(String(200))
    title: Mapped[str | None] = mapped_column(String(1000))
    brand_raw: Mapped[str | None] = mapped_column(String(200))
    brand_id: Mapped[int | None] = mapped_column(ForeignKey("brands.id"))
    category_raw: Mapped[str | None] = mapped_column(String(500))
    category_id: Mapped[int | None] = mapped_column(ForeignKey("categories.id"))
    gtin: Mapped[str | None] = mapped_column(String(14))
    mpn: Mapped[str | None] = mapped_column(String(100))
    model: Mapped[str | None] = mapped_column(String(200))
    # Whatever the source called its attributes, before anything is resolved to the
    # canonical registry. A key nobody has mapped stays here and simply takes no part in
    # identity — the cost of not mapping it is the slow path, not lost data.
    attributes: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")
    # Canonical, parsed, and scoped to the category: `{"storage_gb": 128, "color": "black"}`.
    # Apart from `attributes` because that one is the shop's own names untouched, and
    # mixing our vocabulary into it would leave no way to tell which is which. This is what
    # an identity key is computed from, and its being empty is why that rung has no
    # producer yet.
    identity: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")
    price: Mapped[Decimal | None] = mapped_column(Numeric(12, 2))
    currency_code: Mapped[str | None] = mapped_column(String(3))
    condition: Mapped[str] = mapped_column(String(12), default="new", server_default="new")
    availability: Mapped[str] = mapped_column(
        String(15), default="unknown", server_default="unknown"
    )
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        UniqueConstraint("raw_offer_id", "ruleset_version", name="uq_reading_per_ruleset"),
        Index("ix_normalized_offers_gtin", "gtin"),
        Index("ix_normalized_offers_brand_raw", "brand_raw"),
    )


class PriceEvent(Base):
    """What a listing cost at a moment. A fact, and deliberately not an opinion.

    Keyed by the offer rather than by the variant. "SKU-1 at RD cost 1179 on the first of
    January" was true then and stays true whatever that listing later turns out to be — so a
    wrong match cannot poison the history, and correcting one does not mean rewriting months
    of rows. `variant_id` is carried alongside as a hint for queries and is rewritten when a
    match changes, which touches one listing's rows rather than the table.

    Changes only, never snapshots. Daily snapshots of a million offers are some 365 million
    rows a year; recording the moves is smaller by more than an order of magnitude. A row is
    written when the price moves *or* the availability does, because going out of stock is a
    gap that means as much on a chart as a number.
    """

    __tablename__ = "price_events"

    # The partition key has to be part of the primary key, which is why this is composite.
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    at: Mapped[datetime] = mapped_column(TimestampTZ, primary_key=True, server_default=func.now())
    offer_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    # Denormalized from the offer so a chart can group without a join. They never change for
    # a given offer, unlike the variant.
    seller_id: Mapped[int] = mapped_column(Integer, nullable=False)
    market_code: Mapped[str] = mapped_column(String(2), nullable=False)
    condition: Mapped[str] = mapped_column(String(12), nullable=False)
    variant_id: Mapped[int | None] = mapped_column(Integer)
    # Which channel quoted it. Two channels of one shop can disagree, and a series that
    # cannot say which one said what is a series nobody can explain.
    source_id: Mapped[int | None] = mapped_column(Integer)
    price: Mapped[Decimal | None] = mapped_column(Numeric(12, 2))
    currency_code: Mapped[str | None] = mapped_column(String(3))

    __table_args__ = (
        CheckConstraint("price is null or price >= 0", name="price_not_negative"),
        Index("ix_price_events_offer_at", "offer_id", "at"),
        Index("ix_price_events_variant_at", "variant_id", "condition", "at"),
        # Monthly from the first migration. Retrofitting partitioning onto a table of this
        # size is its own project, and there are no foreign keys out of it for the same
        # reason: a partitioned table cannot be referenced, and the rows are facts that
        # should outlive anything that might be deleted.
        {"postgresql_partition_by": "RANGE (at)"},
    )


class AvailabilityEvent(Base):
    """Whether a listing could be bought, and when.

    Its own table rather than a column on the price, because availability arrives through
    channels that carry no price — a stock ping, a webhook, a faster poll of the same page.
    Recording one of those as a price event would mean repeating the last known price and
    calling it an observation, which asserts something nobody quoted at that moment.

    They also move at different rates: stock can flip several times a day while a price
    changes in a week, so keeping them together would multiply the larger table by the
    churn of the smaller fact.
    """

    __tablename__ = "availability_events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    at: Mapped[datetime] = mapped_column(TimestampTZ, primary_key=True, server_default=func.now())
    offer_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    seller_id: Mapped[int] = mapped_column(Integer, nullable=False)
    market_code: Mapped[str] = mapped_column(String(2), nullable=False)
    condition: Mapped[str] = mapped_column(String(12), nullable=False)
    variant_id: Mapped[int | None] = mapped_column(Integer)
    source_id: Mapped[int | None] = mapped_column(Integer)
    availability: Mapped[str] = mapped_column(String(15), nullable=False)

    __table_args__ = (
        CheckConstraint(
            "availability in ('in_stock', 'out_of_stock', 'preorder', 'unknown')",
            name="availability_known",
        ),
        Index("ix_availability_events_offer_at", "offer_id", "at"),
        Index("ix_availability_events_variant_at", "variant_id", "condition", "at"),
        {"postgresql_partition_by": "RANGE (at)"},
    )


class OfferMatch(Base):
    """Which variant a listing is, and how we came to think so.

    An opinion with a history, never a column on the offer. Re-matching supersedes rather
    than overwrites, so a bad rule can be rolled back, a human override survives the next
    pass, and a link can explain itself when it turns out to be wrong.

    It only ever means "this offer is this variant". What to do about an offer nobody could
    place is `match_queue`, which is a different question with different state.
    """

    __tablename__ = "offer_matches"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    offer_id: Mapped[int] = mapped_column(ForeignKey("offers.id", ondelete="CASCADE"))
    variant_id: Mapped[int] = mapped_column(ForeignKey("variants.id", ondelete="CASCADE"))
    # Which rung of the ladder fired. Kept because trust in them differs wildly: a barcode
    # is proof, a model string parsed out of a title is a guess that happened to land.
    method: Mapped[str] = mapped_column(String(20))
    confidence: Mapped[Decimal] = mapped_column(Numeric(4, 3))
    # What the link is made of: which signal, which values agreed. Without it a wrong match
    # cannot be argued with, only deleted.
    evidence: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")
    decided_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    decided_by: Mapped[str] = mapped_column(String(10), default="rule", server_default="rule")
    superseded_at: Mapped[datetime | None] = mapped_column(TimestampTZ)

    __table_args__ = (
        CheckConstraint(
            "method in ('gtin', 'brand_mpn', 'brand_model', 'identity_key', 'judge', 'human')",
            name="method_known",
        ),
        CheckConstraint("decided_by in ('rule', 'judge', 'human')", name="decided_by_known"),
        CheckConstraint("confidence between 0 and 1", name="confidence_is_a_fraction"),
        # One live opinion per listing. Superseded rows stay, which is the point.
        Index(
            "uq_offer_matches_active",
            "offer_id",
            unique=True,
            postgresql_where=text("superseded_at is null"),
        ),
        Index("ix_offer_matches_variant_id", "variant_id"),
    )


class MatchQueue(Base):
    """A listing nobody could place, and what was found while trying.

    Not a null variant on a match: this carries work state a verdict has no business
    holding — how often it has been attempted, what the near misses were, and above all
    *why* it failed. "Did not match" is at least six different problems routing to six
    different kinds of work, and one undifferentiated pile is a pile nobody sorts.

    The invariant: an offer has an active match or a row here, never both. A second place
    answering "what is this listing" is a second place to disagree.
    """

    __tablename__ = "match_queue"

    offer_id: Mapped[int] = mapped_column(
        ForeignKey("offers.id", ondelete="CASCADE"), primary_key=True
    )
    reason: Mapped[str] = mapped_column(String(20))
    # The near misses, with why each was considered. What turns "we could not decide" into
    # something a human can finish in one click.
    candidates: Mapped[list] = mapped_column(JSONB, default=list, server_default="[]")
    attempts: Mapped[int] = mapped_column(Integer, default=1, server_default="1")
    last_attempt_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    # Looked at, cannot be decided yet, do not show it again until then.
    snoozed_until: Mapped[datetime | None] = mapped_column(TimestampTZ)
    # The brand the matcher settled on and the model it searched for, normalized as the
    # model rung compares them. Written with the row so the queue can be read by maker and
    # grouped by what one new entry would place: null where the brand did not resolve.
    brand_id: Mapped[int | None] = mapped_column(ForeignKey("brands.id", ondelete="SET NULL"))
    model_key: Mapped[str | None] = mapped_column(String(200))

    __table_args__ = (
        CheckConstraint(
            "reason in ('brand_unknown', 'brand_ambiguous', 'no_signals',"
            " 'signals_unmatched', 'ambiguous', 'low_confidence', 'axis_unpublished')",
            name="reason_known",
        ),
        Index("ix_match_queue_reason", "reason"),
        Index("ix_match_queue_brand_model", "brand_id", "model_key"),
    )


class JudgeVerdict(Base):
    """What an outside model answered, kept so it is asked once.

    The reason this table exists is not saving money on repeats of the same listing — it
    is that the matcher retries everything in the queue on every pass, because the
    catalogue it failed against keeps changing underneath it. Without a store, one queued
    listing would be paid for again on every run, forever.

    Keyed by the question rather than by the offer. `question_hash` covers the state and
    the options exactly as they were sent, so a listing whose title changed, or whose
    candidate brands changed because a brand was added, is a different question and gets
    asked again. That is the behaviour worth having: the same question is never paid for
    twice, and a changed one is never answered from a stale cache.

    A verdict is an input to matching, never a match. The matcher reads this table and
    never calls out — running the ladder stays offline, deterministic and fast, and asking
    is its own explicit pass that an admin starts.
    """

    __tablename__ = "judge_verdicts"

    id: Mapped[int] = mapped_column(primary_key=True)
    # What was being decided. One kind today; attribute and category mapping are the
    # shapes this was built wide enough to hold.
    kind: Mapped[str] = mapped_column(String(20))
    question_hash: Mapped[str] = mapped_column(String(64))
    # What the listing was, and which options it was offered. Stored for the same reason
    # `offer_match.evidence` is: a wrong answer that cannot be inspected can only be
    # deleted, not argued with.
    state: Mapped[dict] = mapped_column(JSONB)
    options: Mapped[list] = mapped_column(JSONB)
    # What each option was described as when asked, by option key: the description is what
    # the model judged on, and it is computed from the catalogue of that day. Null on the
    # answers bought before it was kept.
    criteria: Mapped[dict | None] = mapped_column(JSONB)
    # The full answer, probabilities included. `choice` and `confidence` are lifted out
    # of it because they are what every query filters on.
    answer: Mapped[dict] = mapped_column(JSONB)
    choice: Mapped[str] = mapped_column(String(100))
    confidence: Mapped[Decimal] = mapped_column(Numeric(5, 4))
    # The model that actually answered, not the alias that was asked for: `jev-latest`
    # moves, and a verdict nobody can attribute to a version cannot be re-examined when
    # the next one behaves differently.
    model: Mapped[str] = mapped_column(String(50))
    input_tokens: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    output_tokens: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    # Forgotten rather than deleted: the store stops answering with it, so the next pass
    # asks again, and what it cost stays counted — it was paid for.
    forgotten_at: Mapped[datetime | None] = mapped_column(TimestampTZ)

    __table_args__ = (
        CheckConstraint(
            "kind in ('brand_choice', 'variant_choice', 'colour_choice', 'model_match')",
            name="kind_known",
        ),
        CheckConstraint("confidence between 0 and 1", name="confidence_is_a_fraction"),
        Index("ix_judge_verdicts_kind_created", "kind", "created_at"),
        # One live answer per question; a forgotten one stays beside the one that
        # replaced it.
        Index(
            "uq_judge_verdicts_question_hash",
            "question_hash",
            unique=True,
            postgresql_where=text("forgotten_at is null"),
        ),
    )


class JudgeReview(Base):
    """A person's word on one answer: right or wrong.

    What a threshold is measured against. A confidence has to be evaluated on the data it
    is used on, and this is that data: the answers a person looked at, bucketed by the
    number they came with. One per answer, the latest word standing.
    """

    __tablename__ = "judge_reviews"

    verdict_id: Mapped[int] = mapped_column(
        ForeignKey("judge_verdicts.id", ondelete="CASCADE"), primary_key=True
    )
    correct: Mapped[bool] = mapped_column(Boolean)
    note: Mapped[str | None] = mapped_column(String(500))
    reviewed_by: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    reviewed_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())


class Run(Base):
    """One execution of one channel, and the scheduler's entire memory.

    There is no separate scheduler state because this answers both questions it has: when
    did this last run, and is it running now. `next_run_at` is deliberately not a column —
    it would be a cache of `cron + last run` that goes stale the moment somebody edits the
    schedule, leaving two sources of truth to disagree silently.

    The status is what a run is *for*. A channel that returns three products instead of
    nine hundred has not lied about the three: they are real and writing them harms
    nothing. The damage is concluding that the eight hundred and ninety-seven unseen ones
    are gone — so the contract gates that inference and nothing else, and no staging
    mechanism is needed to hold a batch until it is judged.
    """

    __tablename__ = "runs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    source_id: Mapped[int] = mapped_column(ForeignKey("sources.id", ondelete="CASCADE"))
    kind: Mapped[str] = mapped_column(String(10))
    status: Mapped[str] = mapped_column(String(12), default="running", server_default="running")

    started_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    finished_at: Mapped[datetime | None] = mapped_column(TimestampTZ)

    items_seen: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    items_ingested: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    items_failed: Mapped[int] = mapped_column(Integer, default=0, server_default="0")

    # Measured, per field. `delivers_*` on the channel says what it is shaped to give;
    # this says what it gave. The gap between the two is the alarm: a channel whose gtin
    # was 0.95 last week and is 0.10 today is a shop that changed something, found the day
    # it happens rather than a month later through matching quietly getting worse.
    coverage: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")
    contract: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")
    error: Mapped[str | None] = mapped_column(Text)
    # What the run has done so far, while it does it: the worker's counts as it reads and
    # hands over, then what settling it placed. `items_*` above are the verdict at the end;
    # this is how a person watches one run fill in, step by step.
    progress: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")

    __table_args__ = (
        CheckConstraint("kind in ('full', 'quick', 'reparse')", name="kind_known"),
        CheckConstraint(
            "status in ('queued', 'running', 'ok', 'rejected', 'failed', 'interrupted')",
            name="status_known",
        ),
        # A live run — waiting or working — is exactly a row without finished_at. Without
        # this the status and the timestamp drift apart and "what is live" stops being one
        # query.
        CheckConstraint(
            "(status in ('queued', 'running')) = (finished_at is null)",
            name="finished_matches_status",
        ),
        # One live run per channel and kind, held by the database rather than by the hope
        # that there is only ever one scheduler.
        Index(
            "uq_runs_one_live",
            "source_id",
            "kind",
            unique=True,
            postgresql_where=text("finished_at is null"),
        ),
        # Both "when did this last run" and "the last one that ended ok" read from here.
        Index("ix_runs_source_kind_started", "source_id", "kind", desc("started_at")),
    )


class SchedulerHeartbeat(Base):
    """The scheduler saying it is alive, once per tick. One row.

    The one question `runs` cannot answer. It says when each channel last ran and what is
    running, and with nothing due it says nothing at all — which on 23.09.2026 looked the same
    as a scheduler that had stopped: no source had a schedule, the log was empty, and the only
    health check probed an HTTP port this process does not open. So each tick writes here,
    and a stale `ticked_at` is a scheduler that stopped, whatever else is quiet.
    """

    __tablename__ = "scheduler_heartbeat"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, default=1)
    started_at: Mapped[datetime] = mapped_column(TimestampTZ)
    ticked_at: Mapped[datetime] = mapped_column(TimestampTZ)
    pid: Mapped[int] = mapped_column(Integer)
    running: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    started_last_tick: Mapped[int] = mapped_column(Integer, default=0, server_default="0")

    __table_args__ = (CheckConstraint("id = 1", name="one_row"),)
