"""ORM models. One table per entity, no inheritance tricks."""

from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base

# Timestamps are stored as timestamptz and generated by the database, so every row
# agrees on the clock even with several application instances.
TimestampTZ = DateTime(timezone=True)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(String(320), unique=True)
    password_hash: Mapped[str] = mapped_column(Text)
    full_name: Mapped[str | None] = mapped_column(String(200))
    role: Mapped[str] = mapped_column(String(20), default="customer")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TimestampTZ, server_default=func.now(), onupdate=func.now()
    )
    last_login_at: Mapped[datetime | None] = mapped_column(TimestampTZ)
    # Every token carries the epoch it was minted at; only the current one is accepted.
    # Bumping this ends every session the account has, which is what a password change
    # must do — the tokens are stateless, so revocation has to live on the account.
    # A counter rather than a timestamp because JWT `iat` holds whole seconds, and a
    # token minted in the same second as the change would survive a time comparison.
    token_epoch: Mapped[int] = mapped_column(Integer, default=0, server_default="0")

    __table_args__ = (
        CheckConstraint("role in ('customer', 'admin')", name="role_known"),
        Index("ix_users_role", "role"),
    )


class Product(Base):
    __tablename__ = "products"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(200))
    description: Mapped[str | None] = mapped_column(Text)
    price: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    currency: Mapped[str] = mapped_column(String(3), default="EUR")
    in_stock: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    tags: Mapped[list[str]] = mapped_column(ARRAY(Text), default=list, server_default="{}")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())

    __table_args__ = (
        CheckConstraint("price > 0", name="price_positive"),
        # The service treats names case-insensitively; the database enforces it.
        Index("uq_products_lower_name", func.lower(name), unique=True),
    )


class AuditEntry(Base):
    __tablename__ = "audit_entries"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    request_id: Mapped[str] = mapped_column(String(64))
    # The actor may be deleted later; the trail keeps the email either way, which is
    # why it is denormalised rather than joined.
    actor_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    actor_email: Mapped[str | None] = mapped_column(String(320))
    method: Mapped[str] = mapped_column(String(10))
    path: Mapped[str] = mapped_column(String(512))
    status_code: Mapped[int] = mapped_column(Integer)
    target_type: Mapped[str | None] = mapped_column(String(50))
    target_id: Mapped[str | None] = mapped_column(String(64))
    changes: Mapped[dict | None] = mapped_column(JSONB)
    ip: Mapped[str | None] = mapped_column(String(45))
    user_agent: Mapped[str | None] = mapped_column(String(512))
    duration_ms: Mapped[int] = mapped_column(Integer)

    __table_args__ = (
        # The trail is read newest-first and filtered by actor or time far more often
        # than anything else.
        Index("ix_audit_entries_id_desc", id.desc()),
        Index("ix_audit_entries_created_at", created_at.desc()),
        Index("ix_audit_entries_actor_id", actor_id),
    )


class LoginAttempt(Base):
    """Failed sign-ins, counted per account and per address.

    One row per bucket rather than one per attempt: the limiter only ever needs the
    running count and the current lock, and a row per attempt would make sign-in pay
    for an ever-growing table.
    """

    __tablename__ = "login_attempts"

    scope: Mapped[str] = mapped_column(String(10), primary_key=True)
    key: Mapped[str] = mapped_column(String(320), primary_key=True)
    failures: Mapped[int] = mapped_column(Integer, default=0)
    window_start: Mapped[datetime] = mapped_column(TimestampTZ)
    locked_until: Mapped[datetime | None] = mapped_column(TimestampTZ)
    updated_at: Mapped[datetime] = mapped_column(TimestampTZ)

    __table_args__ = (
        CheckConstraint("scope in ('ip', 'account')", name="scope_known"),
        # Buckets nobody has touched for a while are prunable; nothing else reads this.
        Index("ix_login_attempts_updated_at", "updated_at"),
    )


class Currency(Base):
    """ISO 4217. Reference data, keyed by the code everything else already speaks."""

    __tablename__ = "currencies"

    # Natural key: the code is what arrives in every feed and appears in every URL, so a
    # surrogate id would add a join to almost every query and buy nothing.
    code: Mapped[str] = mapped_column(String(3), primary_key=True)
    name: Mapped[str] = mapped_column(String(100))
    symbol: Mapped[str | None] = mapped_column(String(8))
    # How many decimal places the currency actually has. Two almost everywhere, zero for
    # the yen, three for a few others. It is what says Numeric(12, 2) is the right shape,
    # and the only thing that catches a second currency with different precision.
    minor_units: Mapped[int] = mapped_column(SmallInteger, default=2, server_default="2")

    __table_args__ = (
        CheckConstraint("code = upper(code)", name="code_upper"),
        CheckConstraint("minor_units between 0 and 4", name="minor_units_sane"),
    )


class Country(Base):
    """ISO 3166-1 alpha-2, and the facts that are true whether or not we sell there.

    Not the same thing as a market: a shop in Germany may deliver to Riga while we run no
    German storefront at all. Germany still needs a row here, for its VAT rate and for the
    shop to point at.
    """

    __tablename__ = "countries"

    code: Mapped[str] = mapped_column(String(2), primary_key=True)
    name: Mapped[str] = mapped_column(String(100))
    currency_code: Mapped[str] = mapped_column(ForeignKey("currencies.code"))
    # Standard rate, as a fraction: 0.2100, not 21. It is multiplied, never divided by a
    # hundred somewhere further down.
    #
    # Nullable because an unknown rate has to look unknown. Nothing is computed from this
    # — prices are stored exactly as the buyer sees them — so the rate only ever explains
    # why two prices differ, and a wrong one explains it wrongly and silently.
    #
    # Current rate, not a history: rates change, and when one does this column is updated
    # and past explanations quietly become wrong. That is acceptable only as long as no
    # arithmetic depends on it. The day it does, this becomes a table with valid_from.
    vat_standard_rate: Mapped[Decimal | None] = mapped_column(Numeric(5, 4))
    # Customs, duty and the cross-border VAT rules all differ across this line, so what
    # can be promised to a buyer differs with it.
    is_eu: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")

    __table_args__ = (
        CheckConstraint("code = upper(code)", name="code_upper"),
        CheckConstraint(
            "vat_standard_rate is null or vat_standard_rate between 0 and 1",
            name="vat_is_a_fraction",
        ),
        Index("ix_countries_is_eu", "is_eu"),
    )


class Market(Base):
    """A storefront we run, in one country.

    Not the same thing as a country: `countries` holds every country we have to be able
    to describe — a German shop delivering to Riga needs a row there — while a market is
    a country we have decided to sell in. One storefront per country, which is why the
    country code is the key rather than a column next to one: two markets in the same
    country are impossible by construction rather than by convention.

    Not seeded. Countries and currencies are facts about the world and belong in a
    migration; opening a market is a decision, and it is made through the admin panel so
    that adding one is data rather than a release.
    """

    __tablename__ = "markets"

    # Primary key and foreign key at once, and what `offer` and `price_event` will carry
    # — two characters instead of an eight-byte id is worth a couple of gigabytes there.
    code: Mapped[str] = mapped_column(String(2), ForeignKey("countries.code"), primary_key=True)
    name: Mapped[str] = mapped_column(String(100))
    # The path segment: /lv/, or /latvija/ if that reads better locally. Kept separate
    # from the code rather than derived from it, because the URL is a product decision
    # and the ISO code is not, and moving a URL after launch costs search ranking.
    #
    # Entered, never generated from the name: deriving it would mean a rename silently
    # moves the URL. And this is the one slug in the system where a change moves every
    # page of a storefront rather than a single one, so it needs a redirect story before
    # it is ever edited, not after.
    slug: Mapped[str] = mapped_column(String(32), unique=True)
    # ISO 639-1, ordered, the first one is the default. A language is not a market: the
    # prices, the shops and the delivery are the same whichever one the page is read in,
    # so Russian in Latvia is a toggle here, not a second storefront.
    languages: Mapped[list[str]] = mapped_column(ARRAY(Text))
    # Created, wired into the parsers, mapped, and only then shown. Adding a market is a
    # process, and this is what makes it one.
    is_enabled: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")

    __table_args__ = (
        CheckConstraint("code = upper(code)", name="code_upper"),
        CheckConstraint("cardinality(languages) > 0", name="has_a_language"),
        # A malformed slug is a 404 that looks like an application bug.
        CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),
    )


class Category(Base):
    """The tree products hang from, and the lever over what the storefront shows.

    Two states that have nothing to do with each other: `is_visible` is editorial, and
    `identity_ready` says whether the parser knows how to pull this category's variant
    axes out of an offer. A category can be created and shown long before it is ready —
    its variants simply take the slow path through the matcher.
    """

    __tablename__ = "categories"

    id: Mapped[int] = mapped_column(primary_key=True)
    parent_id: Mapped[int | None] = mapped_column(ForeignKey("categories.id"))
    # Entered, not generated from the name: deriving it would let a rename move the URL.
    slug: Mapped[str] = mapped_column(String(64), unique=True)
    name: Mapped[str] = mapped_column(String(200))
    is_visible: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    # Own visibility AND every ancestor's, recomputed whenever the tree changes. Walking
    # ancestors per query does not survive millions of variants, and a storefront filter
    # has to be a boolean on an index rather than a recursion.
    is_visible_effective: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    identity_ready: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")
    created_at: Mapped[datetime] = mapped_column(TimestampTZ, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TimestampTZ, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="slug_shape"),
        CheckConstraint("parent_id is null or parent_id <> id", name="not_its_own_parent"),
        Index("ix_categories_parent_id", "parent_id"),
        # What the storefront filters on.
        Index("ix_categories_visible_effective", "is_visible_effective"),
    )
