"""add offers raw offers and readings

Revision ID: 0faa2e581778
Revises: 7fd568b6254c
Create Date: 2026-09-21 18:25:57.940692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0faa2e581778'
down_revision: Union[str, Sequence[str], None] = '7fd568b6254c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=2), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('condition', sa.String(length=12), server_default='new', nullable=False),
    sa.Column('condition_grade', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('availability', sa.String(length=15), server_default='unknown', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability in ('in_stock', 'out_of_stock', 'preorder', 'unknown')", name=op.f('ck_offers_availability_known')),
    sa.CheckConstraint("condition in ('new', 'refurbished', 'used')", name=op.f('ck_offers_condition_known')),
    sa.CheckConstraint('price is null or price >= 0', name=op.f('ck_offers_price_not_negative')),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_offers_currency_code_currencies')),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], name=op.f('fk_offers_market_code_markets')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_offers_seller_id_sellers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('seller_id', 'external_id', name='uq_offer_per_seller')
    )
    op.create_index('ix_offers_last_seen_at', 'offers', ['last_seen_at'], unique=False)
    op.create_index('ix_offers_market_code', 'offers', ['market_code'], unique=False)
    op.create_table('raw_offers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_raw_offers_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_raw_offers_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_offers')),
    sa.UniqueConstraint('offer_id', 'content_hash', name='uq_raw_per_content')
    )
    op.create_index('ix_raw_offers_offer_id', 'raw_offers', ['offer_id'], unique=False)
    op.create_index('ix_raw_offers_source_id', 'raw_offers', ['source_id'], unique=False)
    op.create_table('normalized_offers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('raw_offer_id', sa.BigInteger(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('brand_raw', sa.String(length=200), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_raw', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('gtin', sa.String(length=14), nullable=True),
    sa.Column('mpn', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('condition', sa.String(length=12), server_default='new', nullable=False),
    sa.Column('availability', sa.String(length=15), server_default='unknown', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_normalized_offers_brand_id_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_normalized_offers_category_id_categories')),
    sa.ForeignKeyConstraint(['raw_offer_id'], ['raw_offers.id'], name=op.f('fk_normalized_offers_raw_offer_id_raw_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_offers')),
    sa.UniqueConstraint('raw_offer_id', 'ruleset_version', name='uq_reading_per_ruleset')
    )
    op.create_index('ix_normalized_offers_brand_raw', 'normalized_offers', ['brand_raw'], unique=False)
    op.create_index('ix_normalized_offers_gtin', 'normalized_offers', ['gtin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_normalized_offers_gtin', table_name='normalized_offers')
    op.drop_index('ix_normalized_offers_brand_raw', table_name='normalized_offers')
    op.drop_table('normalized_offers')
    op.drop_index('ix_raw_offers_source_id', table_name='raw_offers')
    op.drop_index('ix_raw_offers_offer_id', table_name='raw_offers')
    op.drop_table('raw_offers')
    op.drop_index('ix_offers_market_code', table_name='offers')
    op.drop_index('ix_offers_last_seen_at', table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
