"""name a category in the languages shops use

Revision ID: 222092b703c9
Revises: 83dbba8d2b01
Create Date: 2026-09-22 07:58:16.194576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222092b703c9'
down_revision: Union[str, Sequence[str], None] = '83dbba8d2b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Vocabulary keeps ending up in code and keeps having to be taken back out. A shop puts
    the kind of thing at the front of a title — `Telefons Apple iPhone 18 Pro Max 256GB
    Burgundy` — and reading a model out of that means knowing which words name the category
    and carry no model. They are Latvian words. In a rule they are a list somebody will
    append a Lithuanian one to; here they are rows, and the next country needs rows.

    The table earns itself twice. The same aliases answer which of our categories a shop's
    own section path means — `Mobilie telefoni` at one shop and `Telefoni` at another are
    this category said twice — which is the mapping that has been on the list since the
    beginning and had nowhere to live.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('alias_normalized', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='human', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin in ('rule', 'judge', 'human')", name=op.f('ck_category_aliases_origin_known')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_aliases_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_aliases')),
    sa.UniqueConstraint('category_id', 'alias_normalized', name='uq_alias_per_category')
    )
    op.create_index('ix_category_aliases_normalized', 'category_aliases', ['alias_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_aliases_normalized', table_name='category_aliases')
    op.drop_table('category_aliases')
    # ### end Alembic commands ###
