"""attribute values say whether a title names them

Revision ID: 2d7a339ddb82
Revises: 47106bca48c3
Create Date: 2026-09-25 10:25:49.339255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7a339ddb82'
down_revision: Union[str, Sequence[str], None] = '47106bca48c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute_values', sa.Column('in_title', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute_values', 'in_title')
    # ### end Alembic commands ###
