"""add judge verdicts

Revision ID: 3497f9892c8a
Revises: 494571d7c41f
Create Date: 2026-09-21 19:25:04.092160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3497f9892c8a'
down_revision: Union[str, Sequence[str], None] = '494571d7c41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judge_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('choice', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('brand_choice')", name=op.f('ck_judge_verdicts_kind_known')),
    sa.CheckConstraint('confidence between 0 and 1', name=op.f('ck_judge_verdicts_confidence_is_a_fraction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_judge_verdicts')),
    sa.UniqueConstraint('question_hash', name=op.f('uq_judge_verdicts_question_hash'))
    )
    op.create_index('ix_judge_verdicts_kind_created', 'judge_verdicts', ['kind', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_judge_verdicts_kind_created', table_name='judge_verdicts')
    op.drop_table('judge_verdicts')
    # ### end Alembic commands ###
