"""reread requests a registry change leaves

Revision ID: 38d96781f496
Revises: 7b6b1c301e07
Create Date: 2026-09-26 17:47:30.352543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38d96781f496'
down_revision: Union[str, Sequence[str], None] = '7b6b1c301e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reread_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('after_offer_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('read', sa.Integer(), server_default='0', nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_reread_requests_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_reread_requests_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reread_requests'))
    )
    op.create_index('uq_reread_requests_open', 'reread_requests', ['brand_id', 'category_id'], unique=True, postgresql_where=sa.text('finished_at is null'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reread_requests_open', table_name='reread_requests', postgresql_where=sa.text('finished_at is null'))
    op.drop_table('reread_requests')
    # ### end Alembic commands ###
