"""audit entries indexed by target

Revision ID: 47106bca48c3
Revises: f1612e2433df
Create Date: 2026-09-25 09:33:59.555729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47106bca48c3'
down_revision: Union[str, Sequence[str], None] = 'f1612e2433df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_entries_target', 'audit_entries', ['target_type', 'target_id', sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_entries_target', table_name='audit_entries')
    # ### end Alembic commands ###
