"""add price history

Revision ID: 48571d9d3e73
Revises: 0faa2e581778
Create Date: 2026-09-21 18:34:19.809601

"""
from datetime import date
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48571d9d3e73'
down_revision: Union[str, Sequence[str], None] = '0faa2e581778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=2), nullable=False),
    sa.Column('condition', sa.String(length=12), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('availability', sa.String(length=15), nullable=False),
    sa.CheckConstraint('price is null or price >= 0', name=op.f('ck_price_events_price_not_negative')),
    sa.PrimaryKeyConstraint('id', 'at', name=op.f('pk_price_events')),
    postgresql_partition_by='RANGE (at)'
    )
    op.create_index('ix_price_events_offer_at', 'price_events', ['offer_id', 'at'], unique=False)
    op.create_index('ix_price_events_variant_at', 'price_events', ['variant_id', 'condition', 'at'], unique=False)
    # ### end Alembic commands ###

    # Monthly partitions from the first migration rather than later: retrofitting
    # partitioning onto a table of this size is its own project.
    start = date.today().replace(day=1)
    for offset in range(PARTITION_MONTHS):
        month = _add_months(start, offset)
        nxt = _add_months(start, offset + 1)
        op.execute(
            f"create table price_events_{month:%Y_%m} partition of price_events"
            f" for values from ('{month:%Y-%m-%d}') to ('{nxt:%Y-%m-%d}')"
        )

    # Everything outside the declared range lands here instead of failing. Nothing rolls
    # new partitions yet, and an insert that cannot find one is an outage; rows piling up
    # in a default partition is only awkward. See TODO.md.
    op.execute("create table price_events_default partition of price_events default")


PARTITION_MONTHS = 14


def _add_months(start: date, months: int) -> date:
    month = start.month - 1 + months
    return date(start.year + month // 12, month % 12 + 1, 1)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_events_variant_at', table_name='price_events')
    op.drop_index('ix_price_events_offer_at', table_name='price_events')
    op.drop_table('price_events')
    # ### end Alembic commands ###
