"""let a channel name its category, and a reading carry canonical attributes

Revision ID: 4c205bee71c2
Revises: f41f3175ce67
Create Date: 2026-09-21 21:33:43.893453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c205bee71c2'
down_revision: Union[str, Sequence[str], None] = 'f41f3175ce67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Two columns, one idea. Reading is layered general to specific — anything, then the
    category, then the shop, then the brand, then the product line — and each layer needs
    a key to select by. `sources.category_id` is the category's key, nullable because a
    feed can carry a whole shop and then the category comes from the data.

    `normalized_offers.identity` is where a category's rules put what they worked out:
    canonical names, parsed values, scoped to the kind of product. It is kept apart from
    `attributes`, which is the shop's own names untouched, because mixing our vocabulary
    into theirs leaves no way to tell which is which — and it is what an identity key would
    be computed from, which is why that matching rung has no producer while this is empty.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_offers', sa.Column('identity', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('sources', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_sources_category_id_categories'), 'sources', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sources_category_id_categories'), 'sources', type_='foreignkey')
    op.drop_column('sources', 'category_id')
    op.drop_column('normalized_offers', 'identity')
    # ### end Alembic commands ###
