"""add brands

Revision ID: 5793afbb59d7
Revises: cad9caa29396
Create Date: 2026-09-21 18:04:26.410225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5793afbb59d7'
down_revision: Union[str, Sequence[str], None] = 'cad9caa29396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_brands_slug_shape')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('brand_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('alias_normalized', sa.String(length=200), nullable=False),
    sa.Column('alias_raw', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=10), server_default='spelling', nullable=False),
    sa.Column('origin', sa.String(length=10), server_default='human', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('spelling', 'line')", name=op.f('ck_brand_aliases_kind_known')),
    sa.CheckConstraint("origin in ('rule', 'judge', 'human')", name=op.f('ck_brand_aliases_origin_known')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_aliases_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_aliases')),
    sa.UniqueConstraint('brand_id', 'alias_normalized', name='uq_alias_per_brand')
    )
    op.create_index('ix_brand_aliases_normalized', 'brand_aliases', ['alias_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brand_aliases_normalized', table_name='brand_aliases')
    op.drop_table('brand_aliases')
    op.drop_table('brands')
    # ### end Alembic commands ###
