"""add offer matching and the queue

Revision ID: 661f69288bd6
Revises: c4627001ef1b
Create Date: 2026-09-21 19:00:34.094375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '661f69288bd6'
down_revision: Union[str, Sequence[str], None] = 'c4627001ef1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_queue',
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reason in ('brand_unresolved', 'no_signals', 'signals_unmatched', 'ambiguous', 'low_confidence')", name=op.f('ck_match_queue_reason_known')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_match_queue_offer_id_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', name=op.f('pk_match_queue'))
    )
    op.create_index('ix_match_queue_reason', 'match_queue', ['reason'], unique=False)
    op.create_table('offer_matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by', sa.String(length=10), server_default='rule', nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("decided_by in ('rule', 'judge', 'human')", name=op.f('ck_offer_matches_decided_by_known')),
    sa.CheckConstraint("method in ('gtin', 'brand_mpn', 'brand_model', 'identity_key', 'judge', 'human')", name=op.f('ck_offer_matches_method_known')),
    sa.CheckConstraint('confidence between 0 and 1', name=op.f('ck_offer_matches_confidence_is_a_fraction')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_matches_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_offer_matches_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_matches'))
    )
    op.create_index('ix_offer_matches_variant_id', 'offer_matches', ['variant_id'], unique=False)
    op.create_index('uq_offer_matches_active', 'offer_matches', ['offer_id'], unique=True, postgresql_where=sa.text('superseded_at is null'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_offer_matches_active', table_name='offer_matches', postgresql_where=sa.text('superseded_at is null'))
    op.drop_index('ix_offer_matches_variant_id', table_name='offer_matches')
    op.drop_table('offer_matches')
    op.drop_index('ix_match_queue_reason', table_name='match_queue')
    op.drop_table('match_queue')
    # ### end Alembic commands ###
