"""proxies a channel can go out through

Revision ID: 7b6b1c301e07
Revises: 2d7a339ddb82
Create Date: 2026-09-25 15:40:58.626467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b6b1c301e07'
down_revision: Union[str, Sequence[str], None] = '2d7a339ddb82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxies')),
    sa.UniqueConstraint('name', name=op.f('uq_proxies_name'))
    )
    op.add_column('sources', sa.Column('proxy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_sources_proxy_id_proxies'), 'sources', 'proxies', ['proxy_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sources_proxy_id_proxies'), 'sources', type_='foreignkey')
    op.drop_column('sources', 'proxy_id')
    op.drop_table('proxies')
    # ### end Alembic commands ###
