"""add token epoch and login attempt counters

Revision ID: 7c3e0c08f010
Revises: a6e9a03ea279
Create Date: 2026-09-21 16:27:14.278504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3e0c08f010'
down_revision: Union[str, Sequence[str], None] = 'a6e9a03ea279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('key', sa.String(length=320), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope in ('ip', 'account')", name=op.f('ck_login_attempts_scope_known')),
    sa.PrimaryKeyConstraint('scope', 'key', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_updated_at', 'login_attempts', ['updated_at'], unique=False)
    op.add_column('users', sa.Column('token_epoch', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_epoch')
    op.drop_index('ix_login_attempts_updated_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
