"""add shops sources and sellers

Revision ID: 7fd568b6254c
Revises: b04f46f2e871
Create Date: 2026-09-21 18:21:11.932821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd568b6254c'
down_revision: Union[str, Sequence[str], None] = 'b04f46f2e871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_shop_groups_slug_shape')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_groups')),
    sa.UniqueConstraint('slug', name=op.f('uq_shop_groups_slug'))
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_group_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('is_marketplace', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_shops_slug_shape')),
    sa.CheckConstraint('rating is null or rating between 0 and 5', name=op.f('ck_shops_rating_range')),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], name=op.f('fk_shops_country_code_countries')),
    sa.ForeignKeyConstraint(['shop_group_id'], ['shop_groups.id'], name=op.f('fk_shops_shop_group_id_shop_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops')),
    sa.UniqueConstraint('slug', name=op.f('uq_shops_slug'))
    )
    op.create_index('ix_shops_country_code', 'shops', ['country_code'], unique=False)
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_sellers_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sellers')),
    sa.UniqueConstraint('shop_id', 'external_id', name='uq_seller_per_shop')
    )
    op.create_table('shop_markets',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=2), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['market_code'], ['markets.code'], name=op.f('fk_shop_markets_market_code_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_markets_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shop_id', 'market_code', name=op.f('pk_shop_markets'))
    )
    op.create_index('ix_shop_markets_market_code', 'shop_markets', ['market_code'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('trust', sa.String(length=10), server_default='medium', nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('feed', 'api', 'scrape')", name=op.f('ck_sources_kind_known')),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_sources_slug_shape')),
    sa.CheckConstraint("trust in ('high', 'medium', 'low')", name=op.f('ck_sources_trust_known')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_sources_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_sources_slug'))
    )
    op.create_index('ix_sources_shop_id', 'sources', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sources_shop_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_shop_markets_market_code', table_name='shop_markets')
    op.drop_table('shop_markets')
    op.drop_table('sellers')
    op.drop_index('ix_shops_country_code', table_name='shops')
    op.drop_table('shops')
    op.drop_table('shop_groups')
    # ### end Alembic commands ###
