"""add runs and the collection schedule

Revision ID: 8000ae9e132e
Revises: b8e19b45aca1
Create Date: 2026-09-21 20:09:24.822580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8000ae9e132e'
down_revision: Union[str, Sequence[str], None] = 'b8e19b45aca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CHECKS = (
    # Scheduling a pass that brings back nothing is a config error, not a cheap run.
    ("quick_cron_needs_a_quick_pass", "cron_quick is null or cardinality(delivers_quick) > 0"),
    ("min_items_positive", "min_items is null or min_items > 0"),
    ("drop_is_a_percentage", "max_drop_pct between 0 and 100"),
    ("coverage_is_a_fraction", "min_price_coverage between 0 and 1"),
)


def upgrade() -> None:
    """Upgrade schema.

    `runs` is the scheduler's whole memory: when a channel last ran and whether it is
    running now are both answered here, so there is no scheduler state anywhere else and
    no `next_run_at` column to go stale when somebody edits a cron.

    The partial unique index is the part worth reading twice. One live run per channel and
    kind is held by the database rather than by the hope that only one scheduler process
    exists — and because a live run is defined as a row without `finished_at`, the check
    constraint tying that to the status is what keeps the two from drifting apart.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_ingested', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('contract', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("(status = 'running') = (finished_at is null)", name=op.f('ck_runs_finished_matches_status')),
    sa.CheckConstraint("kind in ('full', 'quick')", name=op.f('ck_runs_kind_known')),
    sa.CheckConstraint("status in ('running', 'ok', 'rejected', 'failed', 'interrupted')", name=op.f('ck_runs_status_known')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_runs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_index('ix_runs_source_kind_started', 'runs', ['source_id', 'kind', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('uq_runs_one_live', 'runs', ['source_id', 'kind'], unique=True, postgresql_where=sa.text('finished_at is null'))
    op.add_column('sources', sa.Column('cron_full', sa.String(length=64), nullable=True))
    op.add_column('sources', sa.Column('cron_quick', sa.String(length=64), nullable=True))
    op.add_column('sources', sa.Column('min_items', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('max_drop_pct', sa.SmallInteger(), server_default='30', nullable=False))
    op.add_column('sources', sa.Column('min_price_coverage', sa.Numeric(precision=3, scale=2), server_default='0.98', nullable=False))
    # ### end Alembic commands ###

    # Autogenerate does not compare check constraints, so these are written by hand and
    # have to be kept beside the model.
    for name, expression in CHECKS:
        op.create_check_constraint(op.f(f"ck_sources_{name}"), "sources", expression)


def downgrade() -> None:
    """Downgrade schema."""
    for name, _ in CHECKS:
        op.drop_constraint(op.f(f"ck_sources_{name}"), "sources", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'min_price_coverage')
    op.drop_column('sources', 'max_drop_pct')
    op.drop_column('sources', 'min_items')
    op.drop_column('sources', 'cron_quick')
    op.drop_column('sources', 'cron_full')
    op.drop_index('uq_runs_one_live', table_name='runs', postgresql_where=sa.text('finished_at is null'))
    op.drop_index('ix_runs_source_kind_started', table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
