"""a composed ruleset version outgrew its column

Revision ID: 83dbba8d2b01
Revises: 4c205bee71c2
Create Date: 2026-09-22 07:49:01.704575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83dbba8d2b01'
down_revision: Union[str, Sequence[str], None] = '4c205bee71c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    A ruleset version is composed of the layers that produced a reading —
    `generic-1+phones-1+ksenukai-1+apple-phones-1` — so that a row says what made it
    without a lookup. Thirty characters held that while there were two layers; the brand
    layer took it to forty-four, and the product layer is still to come.

    It failed as an insert rather than as a validation, which is the worst place to find
    out: the reading was computed correctly and then refused by the column it was going
    into, so an offer of a brand that had rules was the only one that could not be stored.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('normalized_offers', 'ruleset_version',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('normalized_offers', 'ruleset_version',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
