"""the maker's name for a model is a row

211 of 1524 catalogue entries were named `Galaxy S26 S942 5G Dual Sim` and the like: two
shops publish no model field, their rules cut the model out of the title by subtraction,
and what the shop wrote between the name and the capacity stayed on. Recognition instead
of subtraction needs to know which words are a model, and that is the same kind of fact as
which words are a colour — rows, per maker, never a rule.

The table is created empty. It is not reference data we are the source of truth for, and
the seed comes from the corpus — `tools/seed_models.py` reads it off the shops that read
cleanly — so it cannot live in a migration that has to keep working against the code of
its own day.

Revision ID: 87be04a227a1
Revises: e4c2b81a7f56
Create Date: 2026-09-22 20:07:19.256228
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87be04a227a1'
down_revision: Union[str, Sequence[str], None] = 'e4c2b81a7f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('alias_normalized', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('origin', sa.String(length=10), server_default='human', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin in ('rule', 'judge', 'human')", name=op.f('ck_model_aliases_origin_known')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_model_aliases_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_aliases')),
    sa.UniqueConstraint('brand_id', 'alias_normalized', name='uq_model_alias_per_brand')
    )
    op.create_index('ix_model_aliases_normalized', 'model_aliases', ['alias_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_aliases_normalized', table_name='model_aliases')
    op.drop_table('model_aliases')
    # ### end Alembic commands ###
