"""add market table

Revision ID: a9708beb9ae2
Revises: d057e243e488
Create Date: 2026-09-21 17:26:30.610695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9708beb9ae2'
down_revision: Union[str, Sequence[str], None] = 'd057e243e488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_markets_slug_shape')),
    sa.CheckConstraint('cardinality(languages) > 0', name=op.f('ck_markets_has_a_language')),
    sa.CheckConstraint('code = upper(code)', name=op.f('ck_markets_code_upper')),
    sa.ForeignKeyConstraint(['code'], ['countries.code'], name=op.f('fk_markets_code_countries')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_markets')),
    sa.UniqueConstraint('slug', name=op.f('uq_markets_slug'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markets')
    # ### end Alembic commands ###
