"""add the catalogue

Revision ID: b04f46f2e871
Revises: dc79a0811bb5
Create Date: 2026-09-21 18:16:52.523710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04f46f2e871'
down_revision: Union[str, Sequence[str], None] = 'dc79a0811bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('title_override', sa.String(length=400), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer_url', sa.String(length=1000), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_products_slug_shape')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_index('ix_products_brand_id', 'products', ['brand_id'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_table('product_merges',
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('into_id', sa.Integer(), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('decided_by', sa.String(length=10), server_default='human', nullable=False),
    sa.CheckConstraint("decided_by in ('rule', 'judge', 'human')", name=op.f('ck_product_merges_decided_by_known')),
    sa.CheckConstraint('from_id <> into_id', name=op.f('ck_product_merges_not_into_itself')),
    sa.ForeignKeyConstraint(['into_id'], ['products.id'], name=op.f('fk_product_merges_into_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_id', name=op.f('pk_product_merges'))
    )
    op.create_index('ix_product_merges_into_id', 'product_merges', ['into_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('model_normalized', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('title_override', sa.String(length=400), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('image_url_override', sa.String(length=1000), nullable=True),
    sa.Column('kind', sa.String(length=10), server_default='single', nullable=False),
    sa.Column('unit_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'multipack') = (unit_count > 1)", name=op.f('ck_variants_only_multipacks_count')),
    sa.CheckConstraint("kind in ('single', 'multipack', 'bundle')", name=op.f('ck_variants_kind_known')),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_variants_slug_shape')),
    sa.CheckConstraint('unit_count > 0', name=op.f('ck_variants_unit_count_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_variants_brand_id_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_variants_category_id_categories')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_variants_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants')),
    sa.UniqueConstraint('identity_key', name=op.f('uq_variants_identity_key')),
    sa.UniqueConstraint('slug', name=op.f('uq_variants_slug'))
    )
    op.create_index('ix_variants_brand_model', 'variants', ['brand_id', 'model_normalized'], unique=False)
    op.create_index('ix_variants_category_id', 'variants', ['category_id'], unique=False)
    op.create_index('ix_variants_product_id', 'variants', ['product_id'], unique=False)
    op.create_table('variant_attributes',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value_num', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('value_id', sa.Integer(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('source_kind', sa.String(length=10), server_default='param', nullable=False),
    sa.Column('origin', sa.String(length=10), server_default='consensus', nullable=False),
    sa.CheckConstraint("origin in ('consensus', 'human')", name=op.f('ck_variant_attributes_origin_known')),
    sa.CheckConstraint("source_kind in ('param', 'title')", name=op.f('ck_variant_attributes_source_kind_known')),
    sa.CheckConstraint('num_nonnulls(value_num, value_id, value_bool, value_text) = 1', name=op.f('ck_variant_attributes_exactly_one_value')),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_variant_attributes_attribute_id_attributes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_id'], ['attribute_values.id'], name=op.f('fk_variant_attributes_value_id_attribute_values')),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_variant_attributes_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'attribute_id', name=op.f('pk_variant_attributes'))
    )
    op.create_index('ix_variant_attributes_enum', 'variant_attributes', ['attribute_id', 'value_id'], unique=False)
    op.create_index('ix_variant_attributes_number', 'variant_attributes', ['attribute_id', 'value_num'], unique=False)
    op.create_table('variant_components',
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('component_variant_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('bundle_id <> component_variant_id', name=op.f('ck_variant_components_not_its_own_component')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_variant_components_qty_positive')),
    sa.ForeignKeyConstraint(['bundle_id'], ['variants.id'], name=op.f('fk_variant_components_bundle_id_variants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_variant_id'], ['variants.id'], name=op.f('fk_variant_components_component_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bundle_id', 'component_variant_id', name=op.f('pk_variant_components'))
    )
    op.create_table('variant_gtins',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('gtin', sa.String(length=14), nullable=False),
    sa.Column('origin', sa.String(length=10), server_default='rule', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gtin ~ '^[0-9]{8,14}$'", name=op.f('ck_variant_gtins_gtin_digits')),
    sa.CheckConstraint("origin in ('rule', 'judge', 'human')", name=op.f('ck_variant_gtins_origin_known')),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_variant_gtins_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'gtin', name=op.f('pk_variant_gtins'))
    )
    op.create_index('ix_variant_gtins_gtin', 'variant_gtins', ['gtin'], unique=False)
    op.create_table('variant_merges',
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('into_id', sa.Integer(), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('decided_by', sa.String(length=10), server_default='human', nullable=False),
    sa.CheckConstraint("decided_by in ('rule', 'judge', 'human')", name=op.f('ck_variant_merges_decided_by_known')),
    sa.CheckConstraint('from_id <> into_id', name=op.f('ck_variant_merges_not_into_itself')),
    sa.ForeignKeyConstraint(['into_id'], ['variants.id'], name=op.f('fk_variant_merges_into_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_id', name=op.f('pk_variant_merges'))
    )
    op.create_index('ix_variant_merges_into_id', 'variant_merges', ['into_id'], unique=False)
    op.create_table('variant_mpns',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('mpn_normalized', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('mpn_raw', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.String(length=10), server_default='rule', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin in ('rule', 'judge', 'human')", name=op.f('ck_variant_mpns_origin_known')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_variant_mpns_brand_id_brands')),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_variant_mpns_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'mpn_normalized', name=op.f('pk_variant_mpns'))
    )
    op.create_index('ix_variant_mpns_brand_mpn', 'variant_mpns', ['brand_id', 'mpn_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_variant_mpns_brand_mpn', table_name='variant_mpns')
    op.drop_table('variant_mpns')
    op.drop_index('ix_variant_merges_into_id', table_name='variant_merges')
    op.drop_table('variant_merges')
    op.drop_index('ix_variant_gtins_gtin', table_name='variant_gtins')
    op.drop_table('variant_gtins')
    op.drop_table('variant_components')
    op.drop_index('ix_variant_attributes_number', table_name='variant_attributes')
    op.drop_index('ix_variant_attributes_enum', table_name='variant_attributes')
    op.drop_table('variant_attributes')
    op.drop_index('ix_variants_product_id', table_name='variants')
    op.drop_index('ix_variants_category_id', table_name='variants')
    op.drop_index('ix_variants_brand_model', table_name='variants')
    op.drop_table('variants')
    op.drop_index('ix_product_merges_into_id', table_name='product_merges')
    op.drop_table('product_merges')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_brand_id', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
