"""split availability out of the price history

Revision ID: c4627001ef1b
Revises: 48571d9d3e73
Create Date: 2026-09-21 18:41:35.239061

"""
from datetime import date
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4627001ef1b'
down_revision: Union[str, Sequence[str], None] = '48571d9d3e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=2), nullable=False),
    sa.Column('condition', sa.String(length=12), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=15), nullable=False),
    sa.CheckConstraint("availability in ('in_stock', 'out_of_stock', 'preorder', 'unknown')", name=op.f('ck_availability_events_availability_known')),
    sa.PrimaryKeyConstraint('id', 'at', name=op.f('pk_availability_events')),
    postgresql_partition_by='RANGE (at)'
    )
    op.create_index('ix_availability_events_offer_at', 'availability_events', ['offer_id', 'at'], unique=False)
    op.create_index('ix_availability_events_variant_at', 'availability_events', ['variant_id', 'condition', 'at'], unique=False)
    op.add_column('price_events', sa.Column('source_id', sa.Integer(), nullable=True))
    op.drop_column('price_events', 'availability')
    # ### end Alembic commands ###

    # The same partitions the price history got, for the same reason. The helper is
    # repeated rather than imported: a migration has to keep working against the code of
    # its own day, so it cannot reach into the application or into another revision.
    start = date.today().replace(day=1)
    for offset in range(PARTITION_MONTHS):
        month = _add_months(start, offset)
        nxt = _add_months(start, offset + 1)
        op.execute(
            f"create table availability_events_{month:%Y_%m}"
            f" partition of availability_events"
            f" for values from ('{month:%Y-%m-%d}') to ('{nxt:%Y-%m-%d}')"
        )
    op.execute(
        "create table availability_events_default partition of availability_events default"
    )


PARTITION_MONTHS = 14


def _add_months(start: date, months: int) -> date:
    month = start.month - 1 + months
    return date(start.year + month // 12, month % 12 + 1, 1)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_events', sa.Column('availability', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_column('price_events', 'source_id')
    op.drop_index('ix_availability_events_variant_at', table_name='availability_events')
    op.drop_index('ix_availability_events_offer_at', table_name='availability_events')
    op.drop_table('availability_events')
    # ### end Alembic commands ###
