"""a brand can be a line of another

Revision ID: c67d53fb5bc5
Revises: 38d96781f496
Create Date: 2026-09-26 19:13:46.408264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67d53fb5bc5'
down_revision: Union[str, Sequence[str], None] = '38d96781f496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_brands_parent_id_brands'), 'brands', 'brands', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_brands_parent_id_brands'), 'brands', type_='foreignkey')
    op.drop_column('brands', 'parent_id')
    # ### end Alembic commands ###
