"""add attribute registry

Revision ID: cad9caa29396
Revises: 8042c6b0e3e0
Create Date: 2026-09-21 17:51:51.357593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad9caa29396'
down_revision: Union[str, Sequence[str], None] = '8042c6b0e3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('value_type', sa.String(length=10), nullable=False),
    sa.Column('unit_dimension', sa.String(length=20), nullable=True),
    sa.Column('scale', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("(value_type = 'number') or (unit_dimension is null and scale is null)", name=op.f('ck_attributes_units_are_for_numbers')),
    sa.CheckConstraint("key ~ '^[a-z][a-z0-9_]*$'", name=op.f('ck_attributes_key_shape')),
    sa.CheckConstraint("value_type in ('enum', 'number', 'bool', 'text')", name=op.f('ck_attributes_value_type_known')),
    sa.CheckConstraint('scale is null or scale between 0 and 6', name=op.f('ck_attributes_scale_sane')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attributes')),
    sa.UniqueConstraint('key', name=op.f('uq_attributes_key'))
    )
    op.create_table('attribute_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('alias_normalized', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='human', nullable=False),
    sa.CheckConstraint("origin in ('rule', 'judge', 'human')", name=op.f('ck_attribute_aliases_origin_known')),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_attribute_aliases_attribute_id_attributes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_aliases')),
    sa.UniqueConstraint('attribute_id', 'alias_normalized', name='uq_alias_per_attribute')
    )
    op.create_index('ix_attribute_aliases_normalized', 'attribute_aliases', ['alias_normalized'], unique=False)
    op.create_table('attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('canonical', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_attribute_values_attribute_id_attributes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_values')),
    sa.UniqueConstraint('attribute_id', 'canonical', name='uq_value_per_attribute')
    )
    op.create_table('category_attributes',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('identity_bearing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('label_override', sa.String(length=200), nullable=True),
    sa.Column('display_unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_category_attributes_attribute_id_attributes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_attributes_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'attribute_id', name=op.f('pk_category_attributes'))
    )
    op.create_index('ix_category_attributes_attribute_id', 'category_attributes', ['attribute_id'], unique=False)
    op.create_table('attribute_value_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_value_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('alias_normalized', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='human', nullable=False),
    sa.CheckConstraint("origin in ('rule', 'judge', 'human')", name=op.f('ck_attribute_value_aliases_origin_known')),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_attribute_value_aliases_attribute_id_attributes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], name=op.f('fk_attribute_value_aliases_attribute_value_id_attribute_values'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_value_aliases')),
    sa.UniqueConstraint('attribute_id', 'alias_normalized', name='uq_value_alias_per_attribute')
    )
    op.create_index('ix_attribute_value_aliases_normalized', 'attribute_value_aliases', ['alias_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attribute_value_aliases_normalized', table_name='attribute_value_aliases')
    op.drop_table('attribute_value_aliases')
    op.drop_index('ix_category_attributes_attribute_id', table_name='category_attributes')
    op.drop_table('category_attributes')
    op.drop_table('attribute_values')
    op.drop_index('ix_attribute_aliases_normalized', table_name='attribute_aliases')
    op.drop_table('attribute_aliases')
    op.drop_table('attributes')
    # ### end Alembic commands ###
