"""carry a batch of observations, and say which run brought them

Revision ID: cf9b06ccd277
Revises: 8000ae9e132e
Create Date: 2026-09-21 20:24:57.008775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9b06ccd277'
down_revision: Union[str, Sequence[str], None] = '8000ae9e132e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Nullable because a sample loaded by hand has no run behind it, and `SET NULL` rather
    than `CASCADE` because deleting a run must not delete what it collected: the
    observations are facts about a shop, and the run is only how they arrived.

    Worth the column on a table this size. When a run is rejected or its coverage falls off
    a cliff, the question is always "show me what that run actually saw", and a timestamp
    narrows it to a window rather than to a set of rows.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_offers', sa.Column('run_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_raw_offers_run_id', 'raw_offers', ['run_id'], unique=False)
    op.create_foreign_key(op.f('fk_raw_offers_run_id_runs'), 'raw_offers', 'runs', ['run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_raw_offers_run_id_runs'), 'raw_offers', type_='foreignkey')
    op.drop_index('ix_raw_offers_run_id', table_name='raw_offers')
    op.drop_column('raw_offers', 'run_id')
    # ### end Alembic commands ###
