"""add currency and country reference tables

Revision ID: d057e243e488
Revises: 7c3e0c08f010
Create Date: 2026-09-21 17:11:52.124564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd057e243e488'
down_revision: Union[str, Sequence[str], None] = '7c3e0c08f010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.Column('minor_units', sa.SmallInteger(), server_default='2', nullable=False),
    sa.CheckConstraint('code = upper(code)', name=op.f('ck_currencies_code_upper')),
    sa.CheckConstraint('minor_units between 0 and 4', name=op.f('ck_currencies_minor_units_sane')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_currencies'))
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('vat_standard_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_eu', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('code = upper(code)', name=op.f('ck_countries_code_upper')),
    sa.CheckConstraint('vat_standard_rate is null or vat_standard_rate between 0 and 1', name=op.f('ck_countries_vat_is_a_fraction')),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_countries_currency_code_currencies')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_countries'))
    )
    op.create_index('ix_countries_is_eu', 'countries', ['is_eu'], unique=False)
    # ### end Alembic commands ###

    # Reference data belongs in the migration rather than in a startup seed: a country
    # table with no rows is not an empty feature, it is a broken one, and this has to
    # hold in production, where the demo seeding is forced off.
    #
    # Only the markets we serve are seeded. Other countries are added through the admin
    # panel as shops from them appear — asserting the membership and currency of thirty
    # countries here would write facts that move (Bulgaria's euro adoption being the
    # live example), and a wrong fact in reference data is worse than a missing row.
    #
    # vat_standard_rate is left null on purpose. Rates change, they are not ours to
    # guess, and nothing computes with them — the rate only ever explains why two prices
    # differ, so a wrong one explains it wrongly and silently.
    op.execute(
        """
        insert into currencies (code, name, symbol, minor_units)
        values ('EUR', 'Euro', '€', 2)
        """
    )
    op.execute(
        """
        insert into countries (code, name, currency_code, vat_standard_rate, is_eu)
        values ('EE', 'Estonia', 'EUR', null, true),
               ('LT', 'Lithuania', 'EUR', null, true),
               ('LV', 'Latvia', 'EUR', null, true)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_countries_is_eu', table_name='countries')
    op.drop_table('countries')
    op.drop_table('currencies')
    # ### end Alembic commands ###
